### ISSUE TITLE
Rust's Rayon crate: impressive parallel performance

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#102]
I was exploring what's available in Rust for concurrency/parallelism and found this crate http://smallcultfollowing.com/babysteps/blog/2015/12/18/rayon-data-parallelism-in-rust/ It provides not as much: parallel iterators and fork-and-join parallelism. It could be not very interesting if it'd not be extremely performant. Look at this test:
```rust
fn sfib(n: i32) -> i32 {
    if n < 2 { n }
    else { sfib(n - 1) + sfib(n - 2) }
}

fn fib(n: i32) -> i32 {
    if n < 2 { n }
    else { 
        let (n1, n2) = join(|| fib(n - 1), || fib(n - 2));
        n1 + n2 
    }
}

fn main() {
    for i in 1..42 {
        time!("sfib", { print!("fib({}) = {}, ", i, sfib(i)) });
        time!("fib", { print!("fib({}) = {}, ", i, fib(i)) })
    }
}
```
The results:
```
fib(1) = 1, sfib: PT0.000016640S elapsed.
fib(1) = 1, fib: PT0.000000512S elapsed.
fib(2) = 1, sfib: PT0.000000256S elapsed.
fib(2) = 1, fib: PT0.000150528S elapsed.
fib(3) = 2, sfib: PT0.000000512S elapsed.
fib(3) = 2, fib: PT0.000004608S elapsed.
fib(4) = 3, sfib: PT0.000000512S elapsed.
fib(4) = 3, fib: PT0.000004864S elapsed.
fib(5) = 5, sfib: PT0.000000512S elapsed.
fib(5) = 5, fib: PT0.000005632S elapsed.
fib(6) = 8, sfib: PT0.000000512S elapsed.
fib(6) = 8, fib: PT0.000011263S elapsed.
fib(7) = 13, sfib: PT0.000000512S elapsed.
fib(7) = 13, fib: PT0.000004864S elapsed.
fib(8) = 21, sfib: PT0.000000256S elapsed.
fib(8) = 21, fib: PT0.000008192S elapsed.
fib(9) = 34, sfib: PT0.000000256S elapsed.
fib(9) = 34, fib: PT0.000071936S elapsed.
fib(10) = 55, sfib: PT0.000000512S elapsed.
fib(10) = 55, fib: PT0.000069376S elapsed.
fib(11) = 89, sfib: PT0.000000768S elapsed.
fib(11) = 89, fib: PT0.000068863S elapsed.
fib(12) = 144, sfib: PT0.000001024S elapsed.
fib(12) = 144, fib: PT0.000032S elapsed.
fib(13) = 233, sfib: PT0.000002304S elapsed.
fib(13) = 233, fib: PT0.000058880S elapsed.
fib(14) = 377, sfib: PT0.000003072S elapsed.
fib(14) = 377, fib: PT0.000030208S elapsed.
fib(15) = 610, sfib: PT0.000006912S elapsed.
fib(15) = 610, fib: PT0.000052479S elapsed.
fib(16) = 987, sfib: PT0.000008448S elapsed.
fib(16) = 987, fib: PT0.000057856S elapsed.
fib(17) = 1597, sfib: PT0.000007680S elapsed.
fib(17) = 1597, fib: PT0.000084992S elapsed.
fib(18) = 2584, sfib: PT0.000012287S elapsed.
fib(18) = 2584, fib: PT0.000130816S elapsed.
fib(19) = 4181, sfib: PT0.000019712S elapsed.
fib(19) = 4181, fib: PT0.000221695S elapsed.
fib(20) = 6765, sfib: PT0.000050943S elapsed.
fib(20) = 6765, fib: PT0.000336383S elapsed.
fib(21) = 10946, sfib: PT0.000066304S elapsed.
fib(21) = 10946, fib: PT0.000186111S elapsed.
fib(22) = 17711, sfib: PT0.000102911S elapsed.
fib(22) = 17711, fib: PT0.000526846S elapsed.
fib(23) = 28657, sfib: PT0.000173055S elapsed.
fib(23) = 28657, fib: PT0.000385790S elapsed.
fib(24) = 46368, sfib: PT0.000353791S elapsed.
fib(24) = 46368, fib: PT0.000393215S elapsed.
fib(25) = 75025, sfib: PT0.000403710S elapsed.
fib(25) = 75025, fib: PT0.001863671S elapsed.
fib(26) = 121393, sfib: PT0.000761341S elapsed.
fib(26) = 121393, fib: PT0.000976379S elapsed.
fib(27) = 196418, sfib: PT0.001038843S elapsed.
fib(27) = 196418, fib: PT0.001662969S elapsed.
fib(28) = 317811, sfib: PT0.001522169S elapsed.
fib(28) = 317811, fib: PT0.002533876S elapsed.
fib(29) = 514229, sfib: PT0.002333173S elapsed.
fib(29) = 514229, fib: PT0.003947502S elapsed.
fib(30) = 832040, sfib: PT0.004508907S elapsed.
fib(30) = 832040, fib: PT0.006273763S elapsed.
fib(31) = 1346269, sfib: PT0.006024420S elapsed.
fib(31) = 1346269, fib: PT0.010846670S elapsed.
fib(32) = 2178309, sfib: PT0.009938387S elapsed.
fib(32) = 2178309, fib: PT0.016396980S elapsed.
fib(33) = 3524578, sfib: PT0.016001206S elapsed.
fib(33) = 3524578, fib: PT0.026225287S elapsed.
fib(34) = 5702887, sfib: PT0.025745546S elapsed.
fib(34) = 5702887, fib: PT0.042322493S elapsed.
fib(35) = 9227465, sfib: PT0.043349048S elapsed.
fib(35) = 9227465, fib: PT0.084530810S elapsed.
fib(36) = 14930352, sfib: PT0.071417015S elapsed.
fib(36) = 14930352, fib: PT0.110078725S elapsed.
fib(37) = 24157817, sfib: PT0.109070089S elapsed.
fib(37) = 24157817, fib: PT0.178824136S elapsed.
fib(38) = 39088169, sfib: PT0.181352636S elapsed.
fib(38) = 39088169, fib: PT0.286534872S elapsed.
fib(39) = 63245986, sfib: PT0.293695415S elapsed.
fib(39) = 63245986, fib: PT0.469032847S elapsed.
fib(40) = 102334155, sfib: PT0.468343698S elapsed.
fib(40) = 102334155, fib: PT0.750140543S elapsed.
fib(41) = 165580141, sfib: PT0.775336203S elapsed.
fib(41) = 165580141, fib: PT1.225600753S elapsed.
fib(42) = 267914296, sfib: PT1.246988174S elapsed.
fib(42) = 267914296, fib: PT2.002544884S elapsed.
fib(43) = 433494437, sfib: PT2.033778276S elapsed.
fib(43) = 433494437, fib: PT3.183486387S elapsed.
fib(44) = 701408733, sfib: PT3.273918737S elapsed.
fib(44) = 701408733, fib: PT5.130647718S elapsed.
```
At the end of the benchmark it loads all the cores at 100%, so it really does parallel the algorithm. 

The reason I'm writing this is that Hopac cannot do such an amazing work, maybe we could steal something form this crate?

**Comment by polytypic** [comment]
BTW, are the calls to `fib` inside `sfib` intentional?

**Comment by polytypic** [comment]
I took a brief look at Rayon's implementation.  I haven't programmed in Rust, so it is possible that I have misunderstood the code.

Translating Rayon's `join` to F#, it would have a signature roughly like this:

```fs
val join: (unit -> 'a) -> (unit -> 'b) -> 'a * 'b
```

Note that the result type `'a * 'b` is just a plain pair.

Using the above `join` one would write `fib` as:

```fs
let rec fib (n: int) : int =
  if n < 2 then
    n
  else
    let (n1, n2) = join <| fun () -> fib (n-1)
                        <| fun () -> fib (n-2)
    n1 + n2
```

Note that `fib` is just `int -> int` returning a plain result rather than a computation like `int -> Job<int>`.

The approach simply uses the ordinary thread stack, which is convenient and easy if you are limited to working in a low level language where you don't have GC, tail-call optimization or easy and convenient anonymous first-class functions (lack of GC tends to make them more tedious to use).  From a performance perspective, just using the ordinary stack also avoids the potential cost of allocating continuations explicitly.  This is the key that makes it fast even without [a good optimizing compiler](https://github.com/Hopac/Hopac/issues/4#issuecomment-35844172).  For task parallelism this can work quite nicely.

In fact, back when I started working on Hopac, I also thought about implementing a simple task parallel library for C++ (I worked at a company that does a lot of stuff in C++) that would have worked like Rayon (assuming I understood the gist of Rayon correctly), but I never implemented it fully (I did make some toy experiments).

Unfortunately, while it can work for task parallelism, using the ordinary stack makes it unsuitable or difficult to combine with asynchronous and concurrent programming with multiple threads of execution.  Whenever `join` needs to wait for the other branch to complete, it starts to run other tasks.  This is good in the sense that the thread can perform useful work rather than just block.  When `join` starts running other tasks, it does so in the context/with the stack/continuation in which `join` was called.  `join` cannot simply return (or throw) to free up stack space.  Those other tasks may also use `join` and those may also end up waiting.  The stack ends up looking like this:

```
... join ... join ... join ...
```

In the context of performing task parallel programming, this might not cause significant problems.  In a basic task parallel setting you essentially only have a single thread of control.  Consider a call of `fib n`, for example.  It only performs `O(n)` deep recursion.  The other tasks that `join` runs are then `fib m` invocations where `m < n` and each `join` layer on the stack is likely to perform fewer and fewer recursions so stack usage is unlikely to become excessive.

However, if you are running multiple independent threads of execution the stack usage can easily become problematic, because the task execution strategy makes the total stack usage of a single worker thread grow proportional to the sum of the stack usages of the independently running threads of control.

So, if you want to be able to run large numbers of independent threads of control, then the strategy does not work quite so nicely.

**Comment by vasily-kirichenko** [comment]
> BTW, are the calls to fib inside sfib intentional?

Thanks, that was a typo. I've corrected it and re-run the benchmark (the output is updated). The results are not so impressive as before, but still great (~50% slower than the sequential implementation).

**Comment by vasily-kirichenko** [comment]
Thanks for the great explanation! :)
