### ISSUE TITLE
Randomly consume messages from a number of Mailboxes

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#103]
What I'm trying to achieve:
* There is a number of independent queues
* There is a number of independent workers, each of which:
 * Must preferably consume messages from one of the above queues
 * If there is no messages in the "special" queue, it should get messages from all other queues in round-robin fashion

The code:
```fsharp
let worker name preferableMb otherMbs =
    Job.foreverServer <|
    Job.delay (fun _ ->
      Alt.choose 
          [
              preferableMb
              Alt.chooser otherMbs
          ]
        >>= fun x -> Console.WriteLine (sprintf "%s\t%A" name x); timeOutMillis 500
    )
    |> start

let mb1 = Mailbox<int>()
let mb2 = Mailbox<int>()
let mb3 = Mailbox<int>()

worker "*" mb1 [mb2; mb3]
worker "**" mb2 [mb1; mb3]
worker "***" mb3 [mb1; mb2]

for _i in 1..5 do mb1 *<<+ 1 |> run
for _i in 1..10 do mb2 *<<+ 2 |> run
for _i in 1..15 do mb3 *<<+ 3 |> run
```
output:
```
**	2
***	3
*	1
*	1
***	3
**	2
***	3
**	2
*	1
***	3
**	2
*	1
*	1
***	3
**	2
**	2
*	2
***	3
**	2
***	3
*	2
***	3
**	2
*	3
*	3
***	3
**	3
***	3
**	3
*	3
```
It works as expected, but I have a couple of questions:
* Does `Alt.choose` guarantee that it always pick message from the first alternative in the list?
* Does `Alt.chooser` guarantee good random distribution as it's picking messages from its list of alternatives?
* May current behavior change in the future (as it's a detail of implementation as far as I understand)?

**Comment by polytypic** [comment]
[`Alt.choose`](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.choose) does guarantee that it instantiates the alternatives in the sequence order.  The doc "specifies" the semantics in terms of a `foldBack` operation and `<|>`.  It would probably be good to say in English what the order will be and that it is guaranteed.  Note that the order is only relevant when at least one alternative is available at the point it is examined.

`Alt.chooser` has the same caveat as [`Random`](http://hopac.github.io/Hopac/Hopac.html#def:module%20Hopac.Job.Random).  The PRNG should be high quality (currently it is [xorshift128+](http://xoroshiro.di.unimi.it/)).  However, each worker thread stores its own PRNG state and non-worker threads do not.  So, if one invokes the PRNG from a non-worker thread, the state is not so random.  Hmm... It might make sense to make it so that, by default, a PRNG invocation transfers to a worker thread.

The specific PRNG or sequence generated is not specified.  If you need to be able to reproduce sequences of random numbers then you should not use Hopac's built-in generator.  I think that changing the behaviour towards "improved" randomness for `Alt.chooser` and the whole `Random` module would fall into acceptable future changes.

**Comment by polytypic** [comment]
BTW, for performance, it can be better to avoid reconstructing alternatives and jobs unless it is necessary.  So, one could write the `worker` as

```fs
let worker name preferableMb otherMbs =
  Alt.choose
      [
          preferableMb
          Alt.chooser otherMbs
      ]
  >>= fun x -> Console.WriteLine (sprintf "%s\t%A" name x); timeOutMillis 500
  |> Job.foreverServer
  |> start
```

and `a1 <|> a2` would also be slightly faster than `Alt.choose [a1; a2]`.

**Comment by vasily-kirichenko** [comment]
Thanks! Everything is clear now.
