### ISSUE TITLE
Not all symbols are links / tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#106]
![image](https://cloud.githubusercontent.com/assets/873919/15990077/338e89dc-3092-11e6-88fe-b0b4505a3dea.png)

**Comment by polytypic** [comment]
Yes, the way that [FsiRefGen](https://github.com/polytypic/FsiRefGen) looks up symbols is a hack.  Perhaps some day it will use proper parsers to analyze the .fsi files and comments and provide a way to explicitly disambiguate symbols when necessary.

**Comment by cloudRoutine** [comment]
@polytypic what about using [FSharp.Formatting](https://github.com/tpetricek/FSharp.Formatting) instead?

**Comment by haf** [comment]
@cloudRoutine Are there docs for the **command line** FSharp.Formatting available now, which also function according to the spec? Curious since I've spent many days trying to make FSharp.Formatting work like advertised without getting help or working docs.

**Comment by polytypic** [comment]
@cloudRoutine Hmm... In what way?

I'd like to have some markdown support for comments in FsiRefGen.  FSharp.Formatting might help with that.  I'd also like to have a proper .fsi parser in FsiRefGen.  I've thought about perhaps writing a custom parser for that and/or using F# compiler services.

The literate programming stuff in FSharp.Formatting could be nice for some of the documentation. I'll definitely consider that if/when I do a (much needed) major revision to the docs.

OTOH, I personally find the style of [reference documentation](http://tpetricek.github.io/FSharp.Formatting/reference/index.html) (generated with FSharp.Formatting?) in most F# projects very difficult to read:
* Instead of single page, there are multiple pages, so ordinary search in the browser is less useful.
* The reference only visibly lists names of things, so it seems to require more cognitive work to read the reference, because one has to keep track of context (i.e. what kind of list of things (modules, types, values) I'm looking at).

Instead, I find that ML style signatures files are good for both design and documentation purposes, which is what FsiRefGen style docs are based upon.  Much like similar tools for OCaml and SML.

**Comment by cloudRoutine** [comment]
@haf My suspicion is the Razor dependency was probably a part of that. I don't know if the commandline docs are any better at this point. The commandline tool typically isn't used by the projects that rely on it for documentation. 

@polytypic I'm also not a fan of the default API pages, I think one of the biggest weaknesses of FSharp.Formatting is the way it's tied to Razor and doesn't make it as easy to use other templating formats as it could.  I know Tomas stopped using Razor and switched to liquid templates for fssnip.net, but I don't think the proper support has been built into the library proper.

The way you have the documentation page setup is fine for just an API page, and with a different template you could generate a similar page with FSharp.Formatting,  but it's not great when it comes to including explanatory tutorial/sample pages that actually introduce people to how and why they'd want to use Hopac.  I know the most common complaint among people I've showed Hopac to is that they find the docs overwhelming and confusing without any clear idea of an entry point. 

There seems to be a plan to make FSharp.Formatting more accommodating toward alternative documentation production pipelines with better customization, so maybe this should be revisited once that's been completed.

**Comment by polytypic** [comment]
> I know the most common complaint among people I've showed Hopac to is that they find the docs overwhelming and confusing without any clear idea of an entry point.

That is my understanding as well.  What I'd like to do for that is to revise the [Docs](https://github.com/Hopac/Hopac/tree/master/Docs) and the [Programming](https://github.com/Hopac/Hopac/blob/master/Docs/Programming.md) document in particular.  For this work FSharp.Formatting might work well.

However, at the moment my priority is to revise the API and get it to a point where I'd be happy to call it `1.0.0`, and, in particular, get rid of the Scheduler concept, because it should make it easier to improve it (the internal scheduler) and also reduce the API surface considerably, making the library as a whole easier to understand for the user.

**Comment by haf** [comment]
@cloudRoutine Well, for what it's worth I've taken control of the dotLiquid project and it's now being released continuously as things are merged to master; so ping me if you fix the tooling for more command-based pipelines, because I also have a batch of projects I'd like easy docs for – written ones - Vesa's tool is better at displaying complexity in a good way IMO.

**Comment by cloudRoutine** [comment]
I've actually been planning to write an FParsec based F# competitor to dotliquid to make it easier to add custom extensibility :stuck_out_tongue_winking_eye:

**Comment by haf** [comment]
Then please PR that to dotLiquid so we call can benefit. I'm not against taking a dependency on FParsec when it comes to custom languages like liquid. I just want the project to keep its inertia and uptake.
