### ISSUE TITLE
Recommended way to return reply form server

### ISSUE THREAD

**Issue by slav** [Hopac/Hopac#109]
When client sends GET (or similar) message to the server there're several possible ways to pass information back:
1. Client provides reply Ch that server sends reply to
2. Client provides reply IVar that server sends reply to. This could only work for one message, but has benefit of server being able to pass exception (can't fail with Ch, right?)
3. Server has separate reply channel on which client reads reply after sending GET message to the server.

Is there a recommended way for server to communicate back to the client assuming only need to return back one value (e.g. a cell server)? I would imagine #3 has least overhead (don't need to create reply ch or ivar)? Is overhead of creating Ch or IVar the same?

Thank you

**Comment by neoeinstein** [comment]
First, when communicating with a server, you should generally have an abstraction which hides the detail of how the client actually receives the reply (e.g. don't expose the `Ch` directly).

Second, the second option is generally best.

An `IVar` can be though of as an optimized, write-once `Ch`. If you just need a reply, there is a little less overhead by just using an `IVar`.

The third option causes more synchronization than is necessary. If the client isn't ready to read the reply (no `Ch.take`), the server must wait (at the `Ch.give`) for the client to accept the reply message. The server cannot use `Ch.send` because that will lead to race conditions where one client may read a reply destined for another client.

The `IVar` reply pattern is the preferred option, which is why it is given the improved status of having its own custom operators to implement the pattern: `*<-=>=` and `*<-=>-`.

Pointing to my own slides, this demonstrates the general pattern: https://neoeinstein.github.io/hopac-concurrency-with-synchronous-messaging/#/7/2

**Comment by polytypic** [comment]
> can't fail with Ch, right?

You can send a `Choice<'result, exn>`.

The most important consideration when choosing a pattern is the desired semantics and, in particular, at which point should the operation be considered committed to?  [This skeleton of a document](https://github.com/Hopac/Hopac/blob/master/Docs/Client-Server.md) shows a number of client-server call patterns with various semantics.
