### ISSUE TITLE
Use FAKE over shell script for build process?

### ISSUE THREAD

**Issue by cloudRoutine** [Hopac/Hopac#112]
@polytypic are you open to this?

**Comment by polytypic** [comment]
There used to be a FAKE script originally written by @vasily-kirichenko.  Thanks for writing it!  It served its purpose.

The current shell script has the following main advantages:
* It has smaller start up overhead.
* It builds correctly on OS X.  The FAKE script didn't quite work on OS X, because xbuild doesn't quite work like msbuild.
* It does more, because I find it easier to extend.

The functionality is also better suited to my workflow.  Aside from the startup time one could also achieve the same with FAKE, of course.

I've used Bash shell and basic command line tools like find, sed, and grep for daily work and Bash for scripting for a very long time.  Previously one of the first things I've installed on every Windows machine I've used for development has been Cygwin.  While I don't consider myself to be a Bash expert, I know how to do basic things with it.  Bash is certainly not the nicest programming language, but, once you know it, it is quite usable unlike e.g. cmd.

I don't have the same level of experience with FAKE.  The bulk of the work that the build script does is that it executes some sequence of commands.  If I want to do something simple, that I know how to do from the shell, I have to reach for the documentation/source or basically just run the sequence of commands like I would with shell, except that I need to do it more verbosely.  So, for the bulk of the work, which is running sequences commands, I find Bash superior to F#/FAKE.  For more complex algorithms and text/data manipulation I find F# superior to Bash, but currently basic command line tools have sufficed.

FAKE has support for dependencies.  I considered using make instead of bash, but the heaviest parts of the build already perform caching on their own.  So, I just made it so that commands call each other and do nothing if they have already been done.  BTW, back when I started using F# (2008), I used make and the fsc command to build F# projects.  It worked great.  Build files were short (basically just lists of files for build order) and builds were trivially parallelized.  Parallel builds with msbuild became trivial just fairly recently.  I don't like msbuild, but currently much of F# tooling requires msbuild project files.

I'm not opposed to FAKE, but, at the moment, I personally don't see significant advantages for this project over bash.  The current bash script is comparable in length to the FAKE script it replaced (when you compare them with respect to functionality) and I personally find the bash script easier to work with.

What significant advantages would using FAKE bring?

**Comment by cloudRoutine** [comment]
Personally I've had nothing but bad experiences with Cygwin with it wreaking havok across my system breaking the PATH, registry, and all kinds of configuration; but now that Bash is on Windows it'll never have to tarnish my system again :smile: 

Looking at the differences between [run](https://github.com/Hopac/Hopac/blob/master/run) and [build.fsx](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/build.fsx) it seems like most of the things you do with sequences of commands (generating assembly info, setting up the Nuget Package, publishing docs) are handled by built in functionality with FAKE.  I think FAKE can make it easier to deal with more complicated builds that involve a wider variety of tools and dependencies, and I've definitely been spoiled by how easy it is to use uniformly on windows or linux. I suppose I don't mind the verbosity of some parts of FAKE build scripts given the advantage of type safety and clarity.

I can understand the aversion of the tedium of looking up stuff in the FAKE api, that was definitely me for a while, but since I contribute to a wide variety of F# OSS projects these days it's become second nature.  That's probably one of the main advantages from a contributor perspective, most F# OSS devs are pretty familiar with FAKE unless they're just starting out. But at the level of complexity of the current build script you have I don't think it makes a big difference. If you find yourself needing to add more and more logic to the build script, like packaging for a variety of platforms on dotnetcore, then it might be worthwhile  to make the switch.  Until then you should stick with whatever's easiest for your workflow :smile:

**Comment by t0yv0** [comment]
Our company uses FAKE a lot and I have grown to hate its guts. It can't match the clarity of shell, it peridocially fails, updgrades are a pain, etc.  Personally, I will take shell scripts any time. If you want a good POSIX experience on Windows I can recommend MSYS2, I use it daily without issue.

**Comment by cloudRoutine** [comment]
@t0yv0 I've had lots of headaches with MSYS2 as well, I'll stick with vagrant, my VM, and bash for windows.

What kinds of issues/problems do you regularly encounter with FAKE? I definitely run into build issues on the regular, but they're almost always related to msbuild, FCS, npm, paket/nuget, or some other part of the build chain, but almost never FAKE itself.

**Comment by t0yv0** [comment]
Behaving differently on different machines, leaving processes such as MSBuild hanging on the build server, misleading APIs. TBH Fake might be OK and I do not know it well enough, maybe our builds are just overengineered. But I have personally been better off without it. Paket is another pet peeve of mine.

**Comment by dmitry-a-morozov** [comment]
Fake and Paket are good ideas on its own but "The Change Function" has negative value
http://www.amazon.com/gp/product/1591841321/
F# community fell into classic trap of "If you have a hammer (F#) everything ...".
Let's re-write whole ecosystem around us in F# instead of leveraging existing and actually working tools.

**Comment by polytypic** [comment]
Hmm... Let's not turn this into a thread bashing other OS projects.  Like I said, I'm personally familiar with Bash and basic shell utilities and not so familiar with FAKE.  I guess for a lot of F# devs the situation has been different.  Personally I've never encountered major problems with Cygwin, but I've mostly used it for fairly basic shell stuff.  Speaking of Paket, I find it superior to NuGet.  I also have a lot of respect for the developer(s) of Paket and NuGet.

To be frank, I personally find the situation with respect to project build automation in the F#/.Net world unsatisfactory and I believe the situation is due to legacy systems rather than more recent OS projects that attempt/need to deal with and try to (partially) remedy the situation.  Let me put it this way:  My experience is that if I clone a F# project repository of an active project (by that I mean the project is being more or less actively developed rather being stale for years) from GitHub, the chances are that it will not "just build" on my OS X dev machine (or on Windows).

I personally wouldn't mind having a standard way to create basic simple F# projects with minimal redundancy (rather than say a project template with lots of intricate files/structure) and have a tool that would do the whole thing (fetch dependencies, build, test, package, publish, etc...) in a standard way with minimal customization.  IOW, I would personally prefer to be able to easily create many simple basic libraries and applications with minimal customization (think: ~50 lines of JSON total) and redundancy per project, rather than to be able to support complex projects requiring large amounts of customization (think: hundreds of lines of code), which, it seems to me, is what the current tooling is, by necessity for legacy reasons, designed to do.

**Comment by forki** [comment]
@dmitry-a-morozov it easy to say the "F# community fell into a trap", but if you look at the beginning of FAKE and Paket then there was a real need for me.

Regarding FAKE: we had build scripts in our company that needed to do COM interop to run since we needed to automate a weird old IDE. That stuff was written in C# and really hard to maintain with all the recompiling/redistribution after simple change of the build. so I took that stuff removed semicolons and braces and everything was so much easier. Then I opensourced it and FAKE was born. It is now super old tech and @matthid is working on a much more modern version of it.

Regarding Paket: We had trouble with nuget for many many years and at least for 3 years I (and others in the C# world) tried to convince the nuget team to change it's model. They made very clear that they won't accept changes in that direction, so we started to solve our own pain points. At eversy point we tried to play well with the existing ecosystem and just to optimize our own local workflow.

**Comment by isaacabraham** [comment]
@t0yv0 just out of curiousity, what are the issues you have with Paket?

**Comment by xavierzwirtz** [comment]
As far as startup times go, FAKE now caches the compilation of the build script. A script that simply prints "hello world" takes 5 seconds on the first run, but each run after that only takes 200 milliseconds.

**Comment by t0yv0** [comment]
@isaacabraham Paket looks promising but I had moments of pain when using it at work on a fast moving codebase, "in anger". Pain points included XML editing mess, non-NuGet compatible treatment of zipping packages, slowing down when using custom feeds, CI failures, bootstrapper failures, failing to work on different machines, coupling of package installation and dep solver and XML editing commands, coupling of deps across .NET projects, sudden bursts of .NET Core installation.  The tool is still in development - it changed its behavior in the last year.

NuGet is far from ideal but it sees a little more use. 

I agree with @polytypic that most of the problems are not the tools' fault. `.NET` has a big legacy weight to carry and is seeing some instability with .NET Core and friends. Sometimes I am sorely tempted to simply check dependencies into source control. Or even switch stacks. We have bona fide interesting problems at work, and it is a shame when build tools become a distraction.

**Comment by isaacabraham** [comment]
Of course. Whilst I've not experienced any of those Paket issues, I would love it if you raised issues on them in the Paket repo. The main contributors are always interested in constructive feedback to help make it a more usable product, but it won't happen unless we're aware of the use cases and issues that people are facing.

**Comment by forki** [comment]
TBF committing packages into source control is a valid approach. For me personally Paket is just a tool to do the manual steps a bit faster. And more importantly to have better overview about my dependencies. But if you don't have many deps and if they don't change frequently then just commiting the files into a lib folder is probably the best approach you can do.
