### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#127]
Is it possible to throttle a `Stream` by an "elements by second" values? Something like this:
```fsharp
seq { ... }
|> Stream.ofSeq
|> Stream.throttle (perSecond 20)
|> ...
```
No elements must be lost (i.e. it should do back pressure if incoming stream rate is bigger that needed).

**Comment by polytypic** [comment]
Sounds like [`afterEach`](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Stream.afterEach) might work in your case.

If you have a stream source that takes `t` amount of time to produce an element, then with `afterEach u` the time between elements is roughly `t + u`.  It should also be possible to make a combinator that tries to achieve a given rate `t` so that with `rate t` the time between elements would be roughly `t`.

**Comment by vasily-kirichenko** [comment]
Thanks!

Ended up with this (processing input stream with 10 workers at maximum rate = 1 per second):
```fsharp
module Stream =
    let parallelMapJob (degree: int) (j: 'x -> Job<'y>) (s: Stream<'x>) : Stream<'y> =
        let inCh = Ch()
        let inStreamClosed = IVar()
        let outCh = Ch()

        job {
            do! Stream.iterJob (Ch.give inCh) s >>=. IVar.fill inStreamClosed () |> Job.start
            for _ in [1..degree] do
                do! (inCh >>= j >>= Ch.give outCh) |> Job.foreverServer
        } |> start

        Stream.unfoldJob (fun _ -> 
            outCh ^-> fun x -> Some(x, ()) 
            <|>
            inStreamClosed ^-> fun _ -> None
        ) ()

seq { 1..10 }
|> Stream.ofSeq
|> Stream.afterEach (timeOutMillis 1000)
|> Stream.parallelMapJob 10 (fun x ->
    job {
        Console.WriteLine x
        return x
    }
   )
|> Stream.toSeq
|> run
|> Seq.sum
```
(copy-pasted from here https://github.com/Hopac/Hopac/issues/92#issuecomment-216549650 with minimal adjustments)

**Comment by polytypic** [comment]
Note that Hopac now also contains a ready made (and IIRC a bit faster) parallelish map: [`mapPipelinedJob`](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Stream.mapPipelinedJob) and `mapPipelinedFun`.  I added those as I needed the functionality myself.  So, you can drop the `parallelMapJob`.  I call it "pipelined", because streams are fundamentally sequential and I don't want to give the impression that it would be a truly effective parallellization mechanism.

**Comment by vasily-kirichenko** [comment]
I'm on version 0.2.1, it does not include `mapPipelinedFun`. Is it safe to upgrade to the latest? There have been a lot of changes recently.

**Comment by polytypic** [comment]
There are quite a few deprecations between 0.2.1 and current version.  But if you don't mind potentially getting a ton of warnings then it should be fairly safe.  One issue in the latest release is the changes to the Promise API that turned out to be error prone.  The old ways to create promises still work, but generate warnings.

**Comment by vasily-kirichenko** [comment]
OK, thanks, let's upgrade.

**Comment by polytypic** [comment]
I added `Stream.duringEach` for the kind of throttling where you actually do want to roughly aim at a given average time per element.  Here is an example:

```fs
  let inline (^) x = x

  let randomTimeOutMillis min max = Alt.random <| fun r ->
    let t = int (r % (uint64 max - uint64 min) + uint64 min)
    timeOutMillis t ^->. t

  let test n =
    let start = Stopwatch.StartNew ()
    let source () = Stream.indefinitely ^ randomTimeOutMillis 0 1000

    source ()
    |> Stream.take n
    |> Stream.consumeFun ^ fun t ->
         printfn "%A plain  %3dms" start.Elapsed t

    source ()
    |> Stream.afterEach ^ timeOutMillis 1000
    |> Stream.take n
    |> Stream.consumeFun ^ fun t ->
         printfn "%A after  %3dms" start.Elapsed t

    source ()
    |> Stream.duringEach ^ timeOutMillis 1000
    |> Stream.take n
    |> Stream.consumeFun ^ fun t ->
         printfn "%A during %3dms" start.Elapsed t
```

Running `test 20L` gives the following output:

```
00:00:00.1576488 plain  153ms
00:00:00.2253215 during 221ms
00:00:00.2468896 after  244ms
00:00:01.0783881 during  71ms
00:00:01.0783523 plain  916ms
00:00:01.3960721 plain  313ms
00:00:02.0017792 plain  601ms
00:00:02.0422724 during  38ms
00:00:02.0588948 plain   57ms
00:00:02.1386503 after  884ms
00:00:02.1786046 plain  115ms
00:00:02.9503481 plain  768ms
00:00:03.0014354 plain   51ms
00:00:03.2534785 plain  248ms
00:00:03.7342758 after  590ms
00:00:03.7351870 during 731ms
00:00:04.1003132 plain  845ms
00:00:04.3714115 plain  267ms
00:00:04.5802716 plain  204ms
00:00:04.7805773 after   38ms
00:00:04.7805773 plain  198ms
00:00:04.9655979 during 957ms
00:00:05.5510391 plain  766ms
00:00:05.5575898 during 550ms
00:00:05.8140434 plain  258ms
00:00:05.8196720 plain    5ms
00:00:06.0293120 during  18ms
00:00:06.3057120 plain  485ms
00:00:06.4705700 after  682ms
00:00:06.9917063 plain  682ms
00:00:07.2592276 during 244ms
00:00:07.4995643 plain  504ms
00:00:07.9431675 after  464ms
00:00:08.3516039 plain  852ms
00:00:08.6102287 during 595ms
00:00:09.4811373 during 461ms
00:00:09.6259404 after  675ms
00:00:10.1214586 during  97ms
00:00:11.2936779 during 265ms
00:00:11.4575013 after  823ms
00:00:12.9393301 during 907ms
00:00:12.9787406 after  512ms
00:00:13.8574682 during 811ms
00:00:14.2032069 after  220ms
00:00:14.7311408 during 681ms
00:00:15.5234377 after  311ms
00:00:15.8989877 during 845ms
00:00:16.3184764 during 260ms
00:00:16.8427622 after  311ms
00:00:17.2441344 during 182ms
00:00:18.6631350 during 597ms
00:00:18.7536870 after  903ms
00:00:19.7451558 during 675ms
00:00:20.2443917 after  486ms
00:00:21.2817035 after   28ms
00:00:23.1290225 after  839ms
00:00:24.4493359 after  313ms
00:00:26.4266176 after  969ms
00:00:27.8035456 after  369ms
00:00:29.3323187 after  522ms
```

As you can see, `plain` completes in (very) roughly 10 seconds, `during` in roughly 20 seconds and `after` in roughly 30 seconds.  Elements take a random amount of time between 0 and 1 seconds to generate.

**Comment by vasily-kirichenko** [comment]
Thanks, very cool! :)
