### ISSUE TITLE
Job.awaitTaskUnit >> Job.catch doesn't handle exception

### ISSUE THREAD

**Issue by pavelhritonenko** [Hopac/Hopac#134]
I'm trying to use method `SqlBulkCopy.WriteToServerAsync` inside `job` CE in that way:

``` fs
    job {
      // ...
      let! result = copy.WriteToServerAsync buffer |> Job.awaitTaskUnit |> Job.catch
    }
```

I expect that in case of exception inside `WriteToServerAsync` I would get `Choice2Of2` in `result`. Instead of that behavior I get unhandled exception that passed to `UnhandledException` handler of current AppDomain.

There is workaround, and it works as expected - I get `Choice2Of2 (SqlException ...)`

``` fs
    job {
     // ...
     let! result = job { return! copy.WriteToServerAsync buffer |> Job.awaitTaskUnit } |> Job.catch
    }
```

**Comment by polytypic** [comment]
What happens here is that `SqlBulkCopy.WriteToServerAsync` raises the exception synchronously when it is called.  So, when written as in the first example,

```fs
let! result = copy.WriteToServerAsync buffer |> Job.awaitUnitTask |> Job.catch
```

`Job.catch` cannot catch the exception, because it is raised before `Job.catch` is called.  Note that an `Async` workflow written similarly using `Async.AwaitTask` and `Async.Catch` would exhibit the same behaviour.

For this reason I would generally recommend using [`Job.fromUnitTask`](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Job.fromUnitTask) (and [`Job.fromTask`](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Job.fromTask)) to *wrap calls* to `Task` returning operations.  In this case you could write:

```fs
let! result = Job.catch <| Job.fromUnitTask <| fun () -> copy.WriteToServerAsync buffer
```

There is important difference in the way operations whose types are of the form `'x -> Task<'y>` and functions of the form `'x -> Async<'y>` or `'x -> Job<'y>` are expected to behave.  Generally operations that return `Task<_>`s *start the operation immediately before returning* and it is not unexpected that they might raise exceptions before they return.  Functions that return `Async<_>`s or `Job<_>`s *should not perform any effects before they return* and the caller should be able to freely compose the returned operation further and run/start it later zero or more times.  `Job.fromTask` (and `Job.fromUnitTask` and corresponding `Alt` primitives) are specifically designed to take a thunk that calls the `Task` returning operation.  This way the returned `Job<_>` (from `Job.fromTask`) can be made to behave like a `Job<_>` so that it can be composed further and executed multiple times.

**Comment by polytypic** [comment]
It might be a good idea to add a paragraph or two on this subject to documentation.  Perhaps a note in the `Job.fromTask` and `Alt.fromTask` operations and "see also" -pointers in related primitives (dealing with `Task` -> `Job` interop).  PR welcome.
