### ISSUE TITLE
>>-. and >>=. do not behave as the documentation suggests

### ISSUE THREAD

**Issue by mavnn** [Hopac/Hopac#136]
According to the documentation, the two examples below should have the same effect; in practice they do not due to eager evaluation of arguments in F#.

I'm not sure if it's possible to make Hopac behave as the docs describe, but if not it would be nice to update the documents to match reality :)

```fs
open Hopac
open Hopac.Infixes

// should wait, but doesn't
printfn "before sync %A" System.DateTime.Now
Job.result "hello"
>>-. printfn "before async %A" System.DateTime.Now
>>=. timeOutMillis 2000
>>-. printfn "after async %A" System.DateTime.Now // This prints immediately after "before async"
|> run
printfn "after sync %A" System.DateTime.Now

// should wait, and does
printfn "before sync %A" System.DateTime.Now
Job.result "hello"
>>- fun _ -> printfn "before async %A" System.DateTime.Now
>>= fun () -> timeOutMillis 2000
>>- fun () -> printfn "after async %A" System.DateTime.Now
|> run
printfn "after sync %A" System.DateTime.Now
```

**Comment by polytypic** [comment]
Yes.

One way to see this is that free variables in examples, such as

> `xJ >>=. yJ` is equivalent to `xJ >>= fun _ -> yJ`

are indeed meant to be interpreted as variables that stand for values (that have already been evaluated) rather than as meta-variables that would stand for expressions (to be evaluated).

Another alternative for the documentation would be to use e.g. the `'x -> 'y -> 'x` combinator and `let in` expressions to make evaluation order more explicit.

I'm not sure which is better.
