### ISSUE TITLE
.NETStandard1.6 FSharp.Core dependency

### ISSUE THREAD

**Issue by neoeinstein** [Hopac/Hopac#148]
Currently Hopac references the `FSharp.Core` package for its `netstandard1.6` dependency, but it appears that most packages are referencing `Microsoft.FSharp.Core.netcore` for .NET Core.

Update the dependency to be on `Microsoft.FSharp.Core.netcore` instead of `FSharp.Core`

@enricosada, @dsyme Does this appear to be sound advice, or is there going to be a release of a good .NET Core version under `FSharp.Core` in the near future?

**Comment by cdrnet** [comment]
Please don't. The Microsoft package is not an official package of the F# Software Foundation and referencing it would split the ecosystem unnecessarily. Separate NuGet packages per platform are also an anti pattern in the .Net (Standard) platform ecosystem, exactly because of issues like this. I suspect and hope the `Microsoft.FSharp.Core.netcore` package will be deprecated in near future.

**Comment by neoeinstein** [comment]
Part of the reasoning here is that `FSharp.Core` version 4.0.1.7-alpha has a split personality, and is currently recommended _against_.

My proposal on this is to release a prerelease "alpha" version, so that mainline consumers won't pick it up. I will keep Hopac releases which depend on `Microsoft.FSharp.Core.netcore` on that "alpha" track until `FSharp.Core` is fully ready and released.

**Comment by neoeinstein** [comment]
This recommendation may now be moot. `FSharp.Core` was just released at `4.1.0.0`, and is a "good" version.

**Comment by enricosada** [comment]
sry @neoeinstein there was not a know release date for `FSharp.Core` package before, so was the current option (to work with others lib, like suave, argu, etc)
