### ISSUE TITLE
Programming.md

### ISSUE THREAD

**Issue by voronoipotato** [Hopac/Hopac#169]
I arrived here after hearing that Suave may use Hopac. https://twitter.com/henrikfeldt/status/955101969487683584

This is potentially a really great thing. However it does mean that Hopac is going to need to bolster its documentation. Really it seems like the documentation is already there but for some reason it's squirreled away in a repository folder. 

The programming.md starts with a relatively understandable guide which should probably be placed front and center. If you start with how a person can use a thing, and how it might be beneficial to them they're much more likely to take it up than if you show them a long api list, or some other library that inspired you. I had to actually look through the repository to find this document and frankly it was the most helpful document by a mile. 

However it abruptly switches to operators defined by Hopac with no explanation about how to use them. We should be mindful that this is an F# library not a Haskell library, and I think that the Programming.md is a wonderful getting started guide, but it should probably include the information from the Operators.md and a brief description of how they are used. I honestly had to stop at this point because while I had seen the bind operator before, I had never seen a  `>==.` which I have no word for. 

I still think even in it's present state it's the best introductory documentation in the repository and should maybe be listed as part of the Getting Started Guide.

**Comment by voronoipotato** [comment]
Suave actually has excellent documentation for someone wanting to get started. It avoids getting in the weeds and focuses on what's important for using the library. I suggest we use their programming guide as a model for "Getting started". 

I'm actually a good candidate for proofreading this because I know absolutely nothing about Concurrent ML, I've never even used ML. I know very little about the operators you've defined. I've used suave naively and it seemed to work fine for me. So if you can make documentation that I can understand then anyone who has successfully used Suave should be able to use Hopac because I'm a pretty low bar.

**Comment by voronoipotato** [comment]
Ah I see now it's linked by the readme as Guide. For whatever reason none of those links were obvious to me. To describe my actions. 

* I first clicked the github.io link at the top of the repository, and was met with a wall of text, I closed the browser. 

* later, I clicked the very first link in the Readme, "reference" was met with the same wall of text, I closed the browser. 

* Frustrated I started looking through the repository for documents and then I found the Programming.md. 


Possible steps to resolve. Don't make the Github.io page an api dump. Make the first link in the readme the Getting Started Guide. Change `Guide` in readme to `Getting Started Guide`.

Then we should then get into the weeds of making the programming guide more accessible.

**Comment by voronoipotato** [comment]
I just realized that if you scroll down long enough in the github.io page there's useful information there. The type annotations are useless to me, that's why I have an editor. Learning that I have to turn on some special form of GC to even benefit from hopac should probably be in the programming guide. Also with information on how to actually do that.

**Comment by haf** [comment]
I'm not sure what to say in response to this issue, since it's not that actionable. Having better docs is always an issue, and also never an issue for the same reason.

To state the obvious, you don't have to turn on some form of special GC to use Hopac, it's a recommendation of a performance optimisation.

Stating that type annotations are useless isn't very productive either.

Reading the API reference may not be the best way to get started; the programming document should be read instead, like you discovered.

In general I'm happy to interact in a positive constructive manner.

**Comment by voronoipotato** [comment]
I think I had arrived here in a fearful place. There was discussion around moving suave to hopac and I really liked suave. I was afraid that Hopac wasn't approachable enough and could cause people to leave suave, but I was also open to the fact that this could very well be a better tool for the job. Sorry for the abrasive first encounter. I was reacting in fear to what I thought was the rug being pulled out from under me. In the future I'll try to breathe a bit before submitting an issue.

**Comment by voronoipotato** [comment]
When I said the type annotations are useless it was because at the time I had thought that the extent of the documentation was a long list of type annotations, because that's the first thing you see when you open the api, and the api is the first piece of documentation available to you. I hadn't taken the time to realize there was more to it than I had first realized. I was flustered, but it wasn't an appropriate response.

**Comment by haf** [comment]
Understandable. I feel passionately about having software that is approachable. However, me moving to Hopac is something I've done the last 3-4 years and that's after reading lots and lots about multiprocessor programming, interleaved concurrency and having written C# with its Task-based API for soon 14 years. Writing in concurrent programs in Hopac is part of the most fun I've ever had as a programmer, and I would like people to experience that joy.

The only real difference to a Suave user would be that it would say `Job<Thing>` or `HttpContext -> Job<HttpContext option>` or the like instead of `Async`. The code you write would be almost identical.
