### ISSUE TITLE
SynchronizationContext support

### ISSUE THREAD

**Issue by polytypic** [Hopac/Hopac#24]
Hopac currently does not support anything like the `SynchronizationContext` mechanism that would allow the execution of Hopac jobs to be pinned to particular threads (or groups of threads) such as the main UI thread.

The overhead for supporting synchronization contexts is significant.  Just adding the extra field corresponding to such a context, without making any use of the field, would seem to add at least about 10% execution time overhead in many benchmarks.  When execution of a Hopac job needs to be started on a particular synchronization context that is not controlled by Hopac code (like the main UI thread), an operation needs to be posted to the context and the overhead is likely to be an order of magnitude higher than with Hopac's custom scheduler.

Despite the overhead cost, and contrary to my previous opinion, it would seem worth it to support synchronization contexts (and other similar mechanism).  Doing so allows Hopac to be seamlessly used for GUI programming.  Hopac performance will still likely be significantly better than with current F# Async.  So, basically there will be one less reason to use F# Async at all.

**Comment by VesaKarvonen** [comment]
I'm having second thoughts about going through with adding support for synchronization contexts.  I've recently "ported" an iOS application that I originally wrote in Swift (big mistake) to F# using Xamarin UIKit bindings, Hopac, choice streams and async.  I had to work around a few Xamarin bugs (like the broken `=` operator and broken `sprintf`), but overall it was much more pleasant than working with Swift.  Based on that experience, it doesn't seem like intrinsic synchronization context support would really bring benefits for GUI work.  Here is a simple example code snippet:

```fsharp
StreamSrc.tap activity
|> Streams.scanFromFun 0 (fun n on -> if on then n+1 else n-1)
|> Streams.mapFun (fun n -> n > 0)
|> Streams.distinctUntilChangedByFun id
|> Streams.iterJob (fun on -> onMain {
   do if on then spinner.StartAnimating () else spinner.StopAnimating () })
|> queue
```

What the above does is that it implements the logic for showing (and hiding) an activity indicator.  When some activity is started, `true` value is added to the `activity` stream and `false` when the activity finishes.

The interesting part about the above snippet is that it updates the GUI.  All the stream processing is done using Hopac worker threads, except for the part that is explicitly transferred to the main thread as an async workflow.  The `onMain` workflow builder builds an async computation, wraps it as a job, and makes it so that the async computation is started, and remains, on the main thread (unless explicitly switched to some other context).  The `onMain` builder is initialized at the beginning of the app like this:

```fsharp
[<AutoOpen>]
module Util =
  let mutable onMain : Async.OnWithSchedulerBuilder = Unchecked.defaultof<_>

Util.onMain <-
  Async.OnWithSchedulerBuilder (
    SynchronizationContext.Current, run (Job.scheduler ()))
```

There are some more things, like how one can bind Hopac to GUI events, that are probably worth writing about, but it is not really rocket science.  I'll probably write a document on that at some point.

**Comment by vasily-kirichenko** [comment]
@eulerfx 0mq context is usually one for app (process) and it's thread safe. Sockets are safe to access by multiple threads, but such access must be serialized (I used to use MailboxProcessor for it). So it seems very easy to wrap sockets in a class, sends messages via a channel and receive them via a Alt. I don't see where synch context would be neede here.

**Comment by VesaKarvonen** [comment]
FYI, there is now some experimental ("for convenience") support for doing stuff on the main synchronization context.  See [onMain](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.TopLevel.onMain) and [IObservable<'x>.onceAltOnMain](http://hopac.github.io/Hopac/Hopac.html#def:member%20Hopac.Extensions.IObservable.onceAltOnMain).  Using `onMain` one can easily run code on the main synchronization context in the middle of concurrent jobs.  `onceAltOnMain` can be useful for responding to GUI events.  (It is not appropriate for working with observables where waiting for singular events does not lead to useful semantics, but the approach works just fine for most purposes in a GUI.)  For example, you could use it in a similar manner to what is described in Neil Danson's blog [Simplifying State with Async (with XNA/WPF examples)](https://neildanson.wordpress.com/2015/02/10/simplifying-state-with-async/).  (This technique of wrapping events as alternatives is basically what I already used previously in the iOS app I wrote.)  In addition to waiting for single events, you can, of course, combine `onceAltOnMain` alternatives with other alternatives such as timeouts.

**Comment by eulerfx** [comment]
Cool. 

WRT zeromq, what @vasily-kirichenko suggested is a better approach. Access to sockets must be serialized AND may require a memory barrier. With Hopac would be even better since no need to use MBP.

**Comment by VesaKarvonen** [comment]
Note that basic operations in Hopac such as fill, send, give and take already include a memory barrier.  As long as one makes it so that a particular zeromq socket may only be manipulated by one Hopac job at a time then that should already have the required barriers.  However, one should not block in a Hopac job and basic ops on zeromq sockets appear to be blocking.  So, to process zeromq sockets it would likely be better to have a dedicated native thread calling zeromq poll, so that only the dedicated thread is blocked.  I'll look into this after a week or two.

**Comment by eulerfx** [comment]
Yeah poll seems like a way to go. Once the Hopac layer is there though, the zeromq patterns can become quite a bit more intelligible.
