### ISSUE TITLE
Why were the README files removed?

### ISSUE THREAD

**Issue by axefrog** [Hopac/Hopac#41]
Hi, I noticed you removed all of the README files a short while ago. What bearing does this have on the state of of the project? Is it ok to start using right now, or is there some kind of overhaul in progress?

**Comment by VesaKarvonen** [comment]
It is mainly the recognization that I can't really guarantee to have enough time to keep the project up to date (e.g. many small details in the tutorial style documents are currently out of date) and, paradoxically, considering your question, that is also partly because the number of users of Hopac has been very low so it doesn't seem like it would make sense to spend my free time on updating the project.

As I said in another issue, I've recently used Hopac in a small iOS project that will likely not continue for long.  Whether future opportunities to use F# and Hopac emerge is largely out of my hands.

One of the reasons for moving Hopac to its own GitHub organization is to perhaps lower the barrier for others to contribute to the project.

So is it ok to start using it?  I'd like to encourage people to try it.  I do believe that compared to other similar .Net libraries, Hopac offers some real benefits and that there are useful things to learn from Hopac.
