### ISSUE TITLE
Higher order Alt functions

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#42]
I'm trying to implement a higher-order function which should

1. Wait for a message from a channel.
2. Then synchronize on a `Alt` which is returned by a function passed as an argument.

My attempt is as following:

```fsharp
let ch = ch<int>()
let take() = Ch.take ch

let g (f: int -> Alt<_>) = Alt.guard << Job.delay <| fun _ ->
    take() |>>? fun x -> f x
    
run (ch <-+ 0)
```
for
```fsharp
(g (fun _ -> Timer.Global.timeOutMillis 3000 |>>? fun _ -> printfn "g timeout")) <|>?
(Timer.Global.timeOutMillis 10000 |>>? fun _ -> printfn "outer timeout")
|> run
```
It results with ```g timeout```.
And for 
```fsharp
(g (fun _ -> Timer.Global.timeOutMillis 10000 |>>? fun _ -> printfn "g timeout")) <|>?
(Timer.Global.timeOutMillis 3000 |>>? fun _ -> printfn "outer timeout")
|> run
```
it results with ```outer timeout```, which is the desired behavior. 
But if I not give a message to `ch`, then it hungs forever. As I understand, it waits on `take()` and not reaches `fun x -> f x` which is return the timeout. 

How I can fix this?

**Comment by VesaKarvonen** [comment]
The problem here is that the `take` operation blocks.  As mentioned in the documentation of [withNack](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.withNack) you should not block before returning the alternative to synchronize on and the same applies to `guard` (the doc probably should mention it there as well).  This is a fairly natural requirement, but can surprise at first.

I think that in the general case, you would need a more complex synchronization mechanism like transactional events to be able to synchronize on both a take and an event constructed after that.  Events in CML and alternatives in Hopac only have a single synchronization point.

However, assuming that the alternative returned by `f` does not need to be cancelled, you can do with the simpler synchronization mechanism by spawning a new thread.  Consider the following code:

```fsharp
  let g (f: int -> Alt<_>) =
    Alt.guard (Promise.queue (take () |>>? fun x -> f x))
```

The same can be done with an `IVar` and `Job.queue`.

**Comment by VesaKarvonen** [comment]
My previous reply on this is perhaps slightly too pessimistic.  I think that with `Alt.withNack` it is possible to implement more complex scenarios, even involving cancellation, similar to the original problem.  It does require modifying the design/interface slightly.  The negative acknowledgment probably needs to be passed to `f`, for example.  Can you provide a little more context on this example (what does the `f` usually do?), so I could consider more carefully how the problem could perhaps be solved?

I think that related to this question are a kind of "discrete event"  combinators I experimented with a while back (originally in Swift).  I just added the experimental module to Hopac repo:

https://github.com/Hopac/Hopac/blob/master/Libs/Hopac.Experimental/Discrete.fsi
https://github.com/Hopac/Hopac/blob/master/Libs/Hopac.Experimental/Discrete.fs

As you can see, it provides a kind of monadic bind operation for alternatives.  However, semantically, the resulting monad is only valid (i.e. satisfies monad laws) for a subset of alternatives.

Note the warning in the signature file.  The problem is that with the current implementation of alternatives in Hopac, an expression like `Alt.never () <|>? xA` creates an alternative that holds onto the `never` alternative (and I think CML also does this).  So, if you produce such combinations in a loop, you have a leak.  It is possible to fix this by modifying the alternative implementation or one can create a new type of events (building on top of alternatives, think: `type DiscreteEvent<'x> = option<Alt<'x>>`, that optimizes such cases.  In fact, now that I think about it, it might indeed make more sense to have a separate type for such events, because not all alternatives are such events.

**Comment by vasily-kirichenko** [comment]
Thanks! Can you provide an example that shows `DiscreteEvent` usage?

I've ended up with a different solution which does not require Alt binding. What about the context, I'm implementing a bounded object pool: one can execute a function on an instance from it, which then returned back to the pool. Also, if an instance is not used for a while, it's disposed and removed from pool. The full code:

```fsharp
type private PoolEntry<'a when 'a :> IDisposable> = 
    { Value: 'a
      mutable LastUsed: DateTime }
    with static member Create(value: 'a) = { Value = value; LastUsed = DateTime.Now }

/// Bounded pool of disposable objects. If number of given objects is equal to capacity then client will be blocked as it tries to get an instance. 
/// If an object in pool is not used more then inactiveTimeBeforeDispose period of time, it's disposed and removed from the pool. 
/// When the pool is disposing itself, it disposes all objects it caches first.
type ObjectPool<'a when 'a :> IDisposable>(createNew: unit -> 'a, ?capacity: uint32, ?inactiveTimeBeforeDispose: TimeSpan) =
    let capacity = defaultArg capacity 50u
    let inactiveTimeBeforeDispose = defaultArg inactiveTimeBeforeDispose (TimeSpan.FromMinutes 1.)
    let reqCh = ch<'a PoolEntry Ch>()
    let releaseCh = ch<'a PoolEntry>()
    let disposeCh = ch()
    
    let rec loop (available: 'a PoolEntry list, given: uint32) = Job.delay <| fun _ ->
        // an instance returns to pool
        let releaseAlt() =
            releaseCh >>=? fun instance ->
                instance.LastUsed <- DateTime.Now
                loop (instance :: available, (given - 1u))
        // request for an instance
        let reqAlt() =
            reqCh >>=? fun replyCh ->
                let instance, available = 
                    match available with
                    | [] -> PoolEntry.Create (createNew()), []
                    | h :: t -> h, t
                (replyCh <-- instance >>.? loop (available, given + 1u))
        // an instance was inactive for too long
        let expiredAlt() =
            available |> List.map (fun e -> Alt.delay <| fun _ ->
                match (e.LastUsed + inactiveTimeBeforeDispose) - DateTime.Now with
                | t when t <= TimeSpan.Zero -> Alt.always e
                | t -> Timer.Global.timeOut t >>%? e)
            |> Alt.choose >>=? fun entry ->
                entry.Value.Dispose()
                loop (available |> List.filter (fun x -> not <| obj.ReferenceEquals(x, entry)), given)

        // the entire pool is disposing
        let disposeAlt() =
            disposeCh |>>? fun _ -> available |> List.iter (fun x -> x.Value.Dispose())

        // if number of given objects is not reach the capacity, synchronize on request channel as well
        if given < capacity then
            releaseAlt() <|>? expiredAlt() <|>? disposeAlt() <|>? reqAlt()
        else
            releaseAlt() <|>? expiredAlt() <|>? disposeAlt()
    
    do start (loop ([], 0u)) 
     
    let get() = Alt.guard << Job.delay <| fun _ ->
        let replyCh = ch()
        reqCh <-+ replyCh >>% replyCh

    /// Gets an available instance from pool or create a new one, then passes it to function f,
    /// then returns the instance back to the pool (even if the job returned by f raises an exception).
    member __.WithInstanceJob (f: 'a -> #Job<unit>) =
        get() >>=? fun entry -> 
            Job.tryFinallyJob (f entry.Value) (releaseCh <-- entry)

    interface IDisposable with
        member __.Dispose() = run (disposeCh <-- ())
```
It works as expected. 

Do you find the code idiomatic (especially `expiredAlt` function)?

**Comment by VesaKarvonen** [comment]
I do see several issues in the code, but I also find the code easy to read and I do think that it is structured quite idiomatically.

One easy issue to note would be the use of `run` in the `Dispose` method:

```fsharp
    interface IDisposable with
        member __.Dispose() = run (disposeCh <-- ())
```

Basically, you should avoid the use of `run`, unless you really, really, need to get the result synchronously.  In this case, the result is not needed at all, so I would recommend just using `start`:

```fsharp
    interface IDisposable with
        member __.Dispose() = start (disposeCh <-- ())
```

Using `start` is both faster and, in cases like this where the result is not needed, also avoids the possibility of deadlock.  See issue #21 for some more discussion on this topic.

Another easy issue, not really related to Hopac, is the use of `DateTime.Now`. I would recommend using `DateTime.UtcNow` as it is much faster.

The remaining issues are considerably more complicated.  I'll draft solutions and write separate replies on them as separate replies:

* As written, get does not cancel and is not safe to use with non-deterministic choice.

* The expiration logic works, but is expensive.

* Disposal does not wait for objects to be released.

I think these are all non-trivial concurrent programming issues.  It would be interesting to see how one could solve them using just Async, for example.

**Comment by VesaKarvonen** [comment]
The documentation of `withNack` gives several rules of thumb.  For the `get` operation, the relevant one is:

> If you have a non-idempotent operation, you can use withNack to send the arguments, negative acknowledgment token and a channel to the server and then synchronize using a take operation on the channel for the reply.

Here are the original snippets:

```fsharp
    let reqCh = ch<'a PoolEntry Ch>()
```

```fsharp
        let reqAlt() =
            reqCh >>=? fun replyCh ->
                let instance, available =
                    match available with
                    | [] -> PoolEntry.Create (createNew()), []
                    | h :: t -> h, t
                (replyCh <-- instance >>.? loop (available, given + 1u))
```

```fsharp
    let get() = Alt.guard << Job.delay <| fun _ ->
        let replyCh = ch()
        reqCh <-+ replyCh >>% replyCh
```

To see the problem, consider a choice of the form `get () <|> always ...`.  What happens is that the reply channel is sent to the server.  Assuming that the server cannot immediately reply, which is perfectly possible, the `always` operation is committed to.  Later the server gets the reply channel from the `reqCh` and tries to give the `instance` to the client.  But the `client` has already committed to the `always` alternative.  The server will block forever.

Here is one way to implement this correctly:

```fsharp
    let reqCh = ch<Promise<unit> * 'a PoolEntry Ch>()
```
```fsharp
        let reqAlt() =
            reqCh >>=? fun (nack, replyCh) ->
                let instance, available =
                    match available with
                    | [] -> PoolEntry.Create (createNew()), []
                    | h :: t -> h, t
                (replyCh <-- instance >>=? fun () -> loop (available, given + 1u)) <|>?
                (nack >>=? fun () -> loop (instance::available, given))
```

```fsharp
    let get() = Alt.withNack <| fun nack ->
        let replyCh = ch()
        reqCh <-+ (nack, replyCh) >>% replyCh
```

Reconsider a choice of the form `get () <|> always ...`.  What happens is the reply channel is sent to the server.  Assuming that the server cannot immediately reply, which is perfectly possible, the `always` operation is committed to.  Later the server gets the reply channel and the negative acknowledgment from the `reqCh` and tries to give the `instance` to the client or to respond to the negative acknowledgment.  The `client` has already committed to the `always` alternative, so the negative acknowledgment is responded to.

**Comment by VesaKarvonen** [comment]
The expiration logic basically works, but it is quite expensive.  Here is the most relevant part:

```fsharp
        let expiredAlt() =
            available |> List.map (fun e -> Alt.delay <| fun _ ->
                match (e.LastUsed + inactiveTimeBeforeDispose) - DateTime.Now with
                | t when t <= TimeSpan.Zero -> Alt.always e
                | t -> Timer.Global.timeOut t >>%? e)
            |> Alt.choose >>=? fun entry ->
                entry.Value.Dispose()
                loop (available |> List.filter (fun x -> not <| obj.ReferenceEquals(x, entry)), given)
```

What this does is that it builds a non-deterministic choice over timeouts on all the objects in the pool.  Registering a timeout is a logarithmic time operation in the number of live timeouts.  So, the cost of the above operation is greater than `O(log(n) * n)` where `n` is the number of objects in the pool.

To make the expiration logic and the removal of objects from to pool really efficient, one could use a priority queue for storing the objects.  The expire alternative would then only register a timeout for the oldest (and soonest to expire) object.  The cost of this approach, with proper data structures, would be roughly logarithmic in the number of objects (and number of timeouts).  I leave that as an exercise.

Let's consider a different approach that can also improve the time bound.  First we introduce a channel for expirations:

```fsharp
    let maybeExpiredCh = ch<'a PoolEntry>()
```

Then we modify the `releaseAlt` to spawn a thread that sends the entry to the expiration channel after the expiration period:

```fsharp
        let releaseAlt() =
            releaseCh >>=? fun instance ->
                instance.LastUsed <- DateTime.Now
                Job.start (Timer.Global.timeOut inactiveTimeBeforeDispose >>.
                           (maybeExpiredCh <-+ instance)) >>.
                loop (instance :: available, (given - 1u))
```

Finally we modify the expiration alternative to take entries from the expiration channel, check if the object really expired and dispose the object if so:

```fsharp
        let expiredAlt() =
            maybeExpiredCh >>=? fun entry ->
            if entry.LastUsed - DateTime.Now > inactiveTimeBeforeDispose &&
               available |> List.exists (fun x -> obj.ReferenceEquals (x, entry)) then
              entry.Value.Dispose()
              loop (available |> List.filter (fun x -> not <| obj.ReferenceEquals(x, entry)), given)
            else
              loop (available, given)
```

This is not yet very efficient, because it still takes linear time to find and remove an entry from the list.  However, it should be easy to replace the free object list with a `HashSet`.  With the `HashSet` the cost of this approach should also be logarithmic.  The cost to start a job, send and receive a message is `O(1)` and the cost of the `timeOut` is logarithmic.

I'm a sucker for performance, so I would probably implement the approach with a priority queue, but I find this approach interesting in that it makes use of cheap jobs.

**Comment by VesaKarvonen** [comment]
This is probably something that doesn't come up in most usage scenarios of the pool, but the dispose alternative can be seen as a bit problematic in that it only disposes the free objects in the pool, but does not wait for objects that are currently allocated to be released.  Here are the relevant snippets:

```fsharp
        let disposeAlt() =
            disposeCh |>>? fun _ -> available |> List.iter (fun x -> x.Value.Dispose())
```

```fsharp
    member __.WithInstanceJob (f: 'a -> #Job<unit>) =
        get() >>=? fun entry ->
            Job.tryFinallyJob (f entry.Value) (releaseCh <-- entry)
```

Assuming that it is possible to have concurrent `WithInstanceJob` operations running at the time the pool is disposed, then what happens is that the concurrent jobs running `WithInstanceJob` will die when they reach the `releaseCh <-- entry` operation.  This happens because no job is trying to take messages from the `releaseCh`, so each giver job will first block on the give operation and will later be GC'ed once all the give operations have been queued to wait on the channel (at which point the `releaseCh` is no longer reachable).

Here is one way to let this situation to be resolved:

```fsharp
        let disposeAlt() =
            disposeCh >>=? fun _ ->
            available |> List.iter (fun x -> x.Value.Dispose())
            Job.forever (releaseCh |>> fun x -> x.Value.Dispose ())
```

The dispose operation simply drains the `releaseCh`.  As soon as there are no longer live `WithInstanceJob` jobs, the `releaseCh` becomes unreachable and the dispose job (as a continuation of the server loop) will be GC'ed.

BTW, note that now the server loop never returns normally, so one can use `server` rather than `start` to spawn the server loop:

```fsharp
    do server (loop ([], 0u))
```

This avoids an allocation and is recommended for server loops that never return normally.

**Comment by VesaKarvonen** [comment]
Here is the code with all the modifications (except for the `UtcNow` suggestion) I made while writing the replies:

```fsharp
type private PoolEntry<'a when 'a :> IDisposable> =
    { Value: 'a
      mutable LastUsed: DateTime }
    with static member Create(value: 'a) = { Value = value; LastUsed = DateTime.Now }

type ObjectPool<'a when 'a :> IDisposable>(createNew: unit -> 'a,
                                             ?capacity: uint32,
                                             ?inactiveTimeBeforeDispose: TimeSpan) =
    let capacity = defaultArg capacity 50u
    let inactiveTimeBeforeDispose = defaultArg inactiveTimeBeforeDispose (TimeSpan.FromMinutes 1.)
    let reqCh = ch<Promise<unit> * 'a PoolEntry Ch>()
    let releaseCh = ch<'a PoolEntry>()
    let disposeCh = ch()
    let maybeExpiredCh = ch<'a PoolEntry>()

    let rec loop (available: 'a PoolEntry list, given: uint32) = Job.delay <| fun _ ->
        // an instance returns to pool
        let releaseAlt() =
            releaseCh >>=? fun instance ->
                instance.LastUsed <- DateTime.Now
                Job.start (Timer.Global.timeOut inactiveTimeBeforeDispose >>.
                           (maybeExpiredCh <-+ instance)) >>.
                loop (instance :: available, (given - 1u))
        // request for an instance
        let reqAlt() =
            reqCh >>=? fun (nack, replyCh) ->
                let instance, available =
                    match available with
                    | [] -> PoolEntry.Create (createNew()), []
                    | h :: t -> h, t
                (replyCh <-- instance >>=? fun () -> loop (available, given + 1u)) <|>?
                (nack >>=? fun () -> loop (instance::available, given))
        // an instance was inactive for too long
        let expiredAlt() =
            maybeExpiredCh >>=? fun entry ->
            if entry.LastUsed - DateTime.Now > inactiveTimeBeforeDispose &&
               available |> List.exists (fun x -> obj.ReferenceEquals (x, entry)) then
              entry.Value.Dispose()
              loop (available |> List.filter (fun x -> not <| obj.ReferenceEquals(x, entry)), given)
            else
              loop (available, given)

        // the entire pool is disposing
        let disposeAlt() =
            disposeCh >>=? fun _ ->
            available |> List.iter (fun x -> x.Value.Dispose())
            Job.forever (releaseCh |>> fun x -> x.Value.Dispose ())

        // if number of given objects is not reach the capacity, synchronize on request channel as well
        if given < capacity then
            releaseAlt() <|>? expiredAlt() <|>? disposeAlt() <|>? reqAlt()
        else
            releaseAlt() <|>? expiredAlt() <|>? disposeAlt()

    do server (loop ([], 0u))

    let get() = Alt.withNack <| fun nack ->
        let replyCh = ch()
        reqCh <-+ (nack, replyCh) >>% replyCh

    /// Gets an available instance from pool or create a new one, then passes it to function f,
    /// then returns the instance back to the pool (even if the job returned by f raises an exception).
    member __.WithInstanceJob (f: 'a -> #Job<unit>) =
        get() >>=? fun entry ->
            Job.tryFinallyJob (f entry.Value) (releaseCh <-- entry)

    interface IDisposable with
        member __.Dispose() = start (disposeCh <-- ())
```

Note that I have not tested the modifications and the use of a list for the free objects is also potentially inefficient as noted.  You should review the modifications and test them.

I'll get back to the DiscreteEvent thing later (tomorrow if I have the time).

**Comment by vasily-kirichenko** [comment]
Thanks a *lot* for your answers! Awesome stuff. 

Your instance expiration logic is very elegant and has made huge performance improvement. I run the following benchmark on the original version and on a version with your suggestion applied:

```fsharp
type Entry = 
    { Value: int }
    interface IDisposable with
        member x.Dispose() = ()

let iteration () =
    let pool = new ObjectPool<_>((fun _ -> { Value = 0 }), 100u)
    let results = ref 0L
    let jobs = 100000
    List.init jobs (fun i -> pool.WithInstanceJob (fun _ -> job { Interlocked.Add(results, int64 i + 1L) |> ignore })) 
    |> Job.conIgnore
    |> run

iteration()
```
* Original: Real: 00:00:12.585, CPU: 00:00:25.786, GC gen0: 3, gen1: 2, gen2: 1
* Improved: Real: 00:00:00.587, CPU: 00:00:03.276, GC gen0: 1, gen1: 1, gen2: 0

Which is ~21 times faster. Wow. 

About using a priority queue instead of list. I maybe wrong but isn't the last element in `available` always the "oldest" one? `available` is actually used as a stack, so instances are naturally ordered by `LastUsed`. If I'm right, it's enough to create a `Timer.Global.timeOut (theLastInstance.LastUsed + inactiveTimeBeforeDispose) - DateTime.UtcNow)` in `expiredAlt`. What do you think?

About `withNack` in `get()`. Yesterday I came myself to the exactly same solution as yours :) Cool. 

About `Job.forever (releaseCh |>> fun x -> x.Value.Dispose ()` in `Dispose` method. Wow. It's very elegant as well. I mentioned the issue with not disposed instances myself but created much more complicated solution. However, I do need to wait for `Dispose` synchronously (at least in tests). Is it dangerous to use `member __.Dispose() = run (disposeCh <-- ())` (I've read #21 and think it's not, but...)?

**Comment by VesaKarvonen** [comment]
Ouch... I noticed a silly bug in the expiration logic I wrote:

```fsharp
            if entry.LastUsed - DateTime.Now > inactiveTimeBeforeDispose &&
```

The subtraction is obviously the wrong way.  It should have been:

```fsharp
            if DateTime.Now - entry.LastUsed > inactiveTimeBeforeDispose &&
```

Sorry about that!  Glancing quickly at the benchmark code it would seem that this shouldn't change the result of the benchmark.

I think you are right that a double ended queue should work.  It should give a similar time bound.  I can't immediately tell which approach would be faster.  One difference between the two is that the spawn-a-timeout approach registers a timeout per release, while the deque approach would register a timeout per loop.

BTW, this was quite an interesting example/problem to think about.  Thanks for asking!  It might be worthwhile to write up some of these examples as tutorials.  Any volunteers? :)

About waiting for the dispose.  Note that the operation `disposeCh <-- ()` only gives a message to the pool server. It doesn't wait for the server to finish processing the disposal.  In fact, you could just as well use an asynchronous send.  If you need to wait until the pool server has finished disposing all the objects, including objects from concurrent `WithInstanceJob` jobs, then a more complex solution will be needed.  I think that it might be useful to create an asynchronous version of the `IDisposable` interface.

About the possibility for deadlock.  Hmm...  As written, `run (disposeCh <-- ())` could deadlock in the case that the operation is executed from a Hopac worker thread.  (If it would use an async send `run (disposeCh <-+ ())`, it should not deadlock.)  Here is what could happen.  The server job could be waiting in the ready queue of the current worker thread.  The worker thread then runs pool dispose.  Now the operation `disposeCh <-- ()` will block, because the server job is not waiting on the `disposeCh` to take a message.  The `run` operation will then deadlock waiting for the `disposeCh <-- ()` operation to complete.

`run` is safe if you use it from a native thread (e.g. main GUI thread or a thread from .Net ThreadPool) that is not a Hopac worker thread (and the Hopac code does not otherwise try to communicate with that thread).  If you use `TopLevel.run` from a Hopac worker thread, then there is a possibility of deadlock, unless the operation can be completed asynchronously.

**Comment by vasily-kirichenko** [comment]
Yes, I mentioned that bug in expiration logic, np. 
About toturials, I'm goning to write a blog post on this example (hope my poor English won't push people away from it).

It turnes out my more compex disposing logic is necessary if I want to `Dispose` to be synchronous. I added "disposing" state to the server here https://github.com/vasily-kirichenko/Hopac.Extras/blob/master/src/Hopac.Extras/ObjectPool.fs#L56-L67 However, it adds `disposed` argument to the server state, which is not very elegant.

**Comment by VesaKarvonen** [comment]
I'm afraid that this `Dispose`

```fsharp
interface IDisposable with
  member __.Dispose() = run (Job.start (dispose <-= ()) >>. hasDisposed)
```

can still deadlock if you try to run it from a Hopac worker thread.  AFAIK, this really is a fundamental limitation as discussed in issue #21 in that there is no perfect solution. Hopac chooses potential deadlocks, while Async (via synchronization contexts) chooses potential stack overflows.

Also note that a write once variable can only be written once, which means that the above `Dispose` cannot be called more than once.  `IVar.tryFill` can be used multiple times on a single write once variable.

There really should be an asynchronous interface for disposables.  Something like:

```fsharp
type IAsyncDisposable =
  abstract DisposeAsync: unit -> Task
```

This interface (or one where `Task` is replaced with `Async<unit>` or `Job<unit>`) would be possible to implement safely so that deadlock cannot happen when `Dispose` is run from inside a job.  I think one could add support for the above kind of asynchronously disposable resources to the job (and async) builder, so one could use the usual `use` syntax within job (and async) workflows.

**Comment by VesaKarvonen** [comment]
As you probably noticed, I added the following experimental `IAsyncDisposable` interface

```fsharp
type IAsyncDisposable =
  abstract DisposeAsync: unit -> Job<unit>
```

and an associated `usingAsync` combinator

```fsharp
val usingAsync: 'x -> ('x -> #Job<'y>) -> Job<'y> when 'x :> IAsyncDisposable
```

to Hopac.  See the Hopac.fsi signature file for the more detailed reference comments.  The idea is that "concurrent object" types using Hopac may implement the `IAsyncDisposable` interface to provide a disposable interface that allows waiting for the disposal to complete.  Such types may also implement the `IDisposable` interface, but that interface cannot safely allow one to wait for the disposable to finish.  The "ordinary" `Dispose` method must be interpreted to mean that disposal is started and may continue in the background after the call to `Dispose` returns.

Here is one way to modify the `ObjectPool` to implement the `IAsyncDisposable` interface.  A write once variable is added to record the status that the object has been disposed:

```fsharp
    let disposed = ivar ()
```

One can also use a write once variable to indicate that disposal must begin:

```fsharp
    let startDispose = ivar ()
```

The `disposeAlt` alternative only drains the `releaseCh` for the number of outstanding operations and then sets the `disposed` variable:

```fsharp
        let disposeAlt() =
            startDispose >>=? fun _ ->
            available |> List.iter (fun x -> x.Value.Dispose())
            Job.forN (int given) (releaseCh |>> fun x -> x.Value.Dispose ()) >>.
            (disposed <-= ())
```

Finally, both of the disposable interface are implemented:

```fsharp
    interface IAsyncDisposable with
        member __.DisposeAsync () = IVar.tryFill startDispose () >>. disposed
    interface IDisposable with
        member __.Dispose() = (__ :> IAsyncDisposable).DisposeAsync () |> start 
```

Here is the benchmark `iteration` function modified to use `Job.usingAsync` so that the job waits until the pool is really disposed:

```fsharp
let iteration () = Job.delay <| fun () ->
    Job.usingAsync (new ObjectPool<_>((fun _ -> { Value = 0 }), 100u)) <| fun pool ->
    let results = ref 0L
    let jobs = 100000
    List.init jobs (fun i -> pool.WithInstanceJob (fun _ -> job { Interlocked.Add(results, int64 i + 1L) |> ignore })) 
    |> Job.conIgnore
```

Here is the full code for reference:

```fsharp
type private PoolEntry<'a when 'a :> IDisposable> =
    { Value: 'a
      mutable LastUsed: DateTime }
    with static member Create(value: 'a) = { Value = value; LastUsed = DateTime.Now }

type ObjectPool<'a when 'a :> IDisposable>(createNew: unit -> 'a,
                                             ?capacity: uint32,
                                             ?inactiveTimeBeforeDispose: TimeSpan) =
    let capacity = defaultArg capacity 50u
    let inactiveTimeBeforeDispose = defaultArg inactiveTimeBeforeDispose (TimeSpan.FromMinutes 1.)
    let reqCh = ch<Promise<unit> * 'a PoolEntry Ch>()
    let releaseCh = ch<'a PoolEntry>()
    let startDispose = ivar ()
    let disposed = ivar ()
    let maybeExpiredCh = ch<'a PoolEntry>()

    let rec loop (available: 'a PoolEntry list, given: uint32) = Job.delay <| fun _ ->
        // an instance returns to pool
        let releaseAlt() =
            releaseCh >>=? fun instance ->
                instance.LastUsed <- DateTime.Now
                Job.start (Timer.Global.timeOut inactiveTimeBeforeDispose >>.
                           (maybeExpiredCh <-+ instance)) >>.
                loop (instance :: available, (given - 1u))
        // request for an instance
        let reqAlt() =
            reqCh >>=? fun (nack, replyCh) ->
                let instance, available =
                    match available with
                    | [] -> PoolEntry.Create (createNew()), []
                    | h :: t -> h, t
                (replyCh <-- instance >>=? fun () -> loop (available, given + 1u)) <|>?
                (nack >>=? fun () -> loop (instance::available, given))
        // an instance was inactive for too long
        let expiredAlt() =
            maybeExpiredCh >>=? fun entry ->
            if DateTime.Now - entry.LastUsed > inactiveTimeBeforeDispose &&
               available |> List.exists (fun x -> obj.ReferenceEquals (x, entry)) then
              entry.Value.Dispose()
              loop (available |> List.filter (fun x -> not <| obj.ReferenceEquals(x, entry)), given)
            else
              loop (available, given)

        // the entire pool is disposing
        let disposeAlt() =
            startDispose >>=? fun _ ->
            available |> List.iter (fun x -> x.Value.Dispose())
            Job.forN (int given) (releaseCh |>> fun x -> x.Value.Dispose ()) >>.
            (disposed <-= ())

        // if number of given objects is not reach the capacity, synchronize on request channel as well
        if given < capacity then
            releaseAlt() <|>? expiredAlt() <|>? disposeAlt() <|>? reqAlt()
        else
            releaseAlt() <|>? expiredAlt() <|>? disposeAlt()

    do start (loop ([], 0u))

    let get() = Alt.withNack <| fun nack ->
        let replyCh = ch()
        reqCh <-+ (nack, replyCh) >>% replyCh

    /// Gets an available instance from pool or create a new one, then passes it to function f,
    /// then returns the instance back to the pool (even if the job returned by f raises an exception).
    member __.WithInstanceJob (f: 'a -> #Job<unit>) =
        get() >>=? fun entry ->
            Job.tryFinallyJob (f entry.Value) (releaseCh <-- entry)

    interface IAsyncDisposable with
        member __.DisposeAsync () = IVar.tryFill startDispose () >>. disposed
    interface IDisposable with
        member __.Dispose() = (__ :> IAsyncDisposable).DisposeAsync () |> start 
```

BTW, there are various ways to further micro optimize the pool.

**Comment by vasily-kirichenko** [comment]
Thanks for `IAsyncDisposable`. 
`Job.forN (int given) (releaseCh |>> fun x -> x.Value.Dispose ())` thing is elegant compared to my clumsy solution. Cool. 
I tried to make `WithInstanceJob` return a value that's returns by the job created by `f`, but it does not compile:
![image](https://cloud.githubusercontent.com/assets/873919/5792979/8cdcad9e-9f42-11e4-9f0c-25bb0fcdf84e.png)

So had to add another method:

```fsharp
member __.WithInstanceJob<'r> (f: 'a -> Job<'r>) : Alt<'r> =
        get() >>=? fun entry -> 
            Job.tryFinallyJob 
                (Job.delay (fun _ -> f entry.Value)) 
                (releaseCh <-- entry)
            
member __.WithInstanceAlt<'r> (f: 'a -> Alt<'r>) : Alt<'r> =
        get() >>=? fun entry -> 
            Job.tryFinallyJob 
                (Job.delay (fun _ -> f entry.Value))  
                (releaseCh <-- entry)
```
Now it compiles but looks ugly. Do you see a better solution?

**Comment by VesaKarvonen** [comment]
Puzzled me for a moment, but here you just need to be either less or more explicit about the type variables:

```fsharp
    member __.WithInstanceJob (f: 'a -> #Job<'r>) : Alt<'r> =
    // or
    member __.WithInstanceJob<'r, 'rJ when 'rJ :> Job<'r>> (f: 'a -> 'rJ) : Alt<'r> =
```

BTW, if you are interested, I could add you to the Hopac GitHub organization and, if you prefer, you could put Hopac.Extras under the Hopac organization?

**Comment by vasily-kirichenko** [comment]
Thanks! 

Yes, I think it's a good idea to move my little project under Hopac umbrella. However, I'm not sure `Hopac.Extras` is a good name (especially considering that `Hopac.Extra` exists). I struggle to find a better name for it.

**Comment by vasily-kirichenko** [comment]
Thanks, I've transferred my repository. 

What do you think about adding FAKE support to Hopac? One of the benefits would be that making and publishing NuGet packages would become a part of the build process and take almost no time (as little as writing single line in release_notes.md file). Currently I have to include Hopac binaries right into Hopac.Extras repository instead of referencing the fresh NuGet package. 

Also it would be great to add AppVeyor (or another) CI support. 

What do you think?

**Comment by VesaKarvonen** [comment]
Feel free to publish/automate (NuGet) packages/build for Hopac. :)

I had some basic AppVeyor and Travis files for Hopac, but you can delete/rewrite those.

**Comment by vasily-kirichenko** [comment]
OK, I'll do this next week.

**Comment by VesaKarvonen** [comment]
That would be cool!  Thanks!

**Comment by vasily-kirichenko** [comment]
I could publish Hopac NuGet package periodically, if you don't mind. To do this you need to make me an owner of Hopac (and Hopac.Extra - I create a build.fsx for it later) packages. Fully automatic publishing by a CI server is not common and I'm not sure is possible due to API key security problem.
