### ISSUE TITLE
timeOut ... |> start causes memory leak

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#50]
Server should process requests withing given timeout. So, I create `timedOut` ivar and start a job that fills the ivar after the timeout. 
The problem is than it cases memory leak. Profiler shows constantly increasing number of object of the following types:

![image](https://cloud.githubusercontent.com/assets/873919/6037825/9d2a592a-ac68-11e4-8e8c-949695550ddc.png)

All of them are created by `ProcessRunner.start` and `File.startReading`.

If I comment the timeout logic, as in the snippet below, then the leak goes away:

```fsharp
Job.foreverServer (
    reqCh >>= fun req ->
        Job.usingAsync (ProcessRunner.start exePath req.Args) <| fun runner ->
        Job.usingAsync (File.startReading req.LogPath) <| fun logFile ->
            //let timedOut = ivar()
            //start (timeOut req.Timeout >>=? fun _ -> timedOut <-= ())
                                    
            let processExitedAlt() = runner.ProcessExited |>>? fun x ->
                x |> Choice.mapError (fun e -> ProcessRunError (exePath, e))

            let rec running() = Job.delay <| fun _ ->
                processExitedAlt() .>>? timeOutMillis 500 >>=? exited <|>? 
                (logFile.NewLine >>=? fun line -> 
                    match LogParser.parseLine line with
                    | None -> running()
                    | Some status -> 
                        runner.Kill() >>. stopping status)// <|>?
                //(timedOut |>>? fun _ -> Fail (TimeOut req.Timeout))
            
            and stopping logStatus = Job.delay <| fun _ ->
                (processExitedAlt() |>>? fun exitResult -> 
                    combineResults logStatus exitResult) <|>?
                (timeOutMillis 5000 >>%? (logStatus <!!> LogFileError)) 

            and exited exitResult = Job.delay <| fun _ ->
                (logFile.NewLine >>=? fun line -> 
                    match LogParser.parseLine line with
                    | None -> exited exitResult
                    | Some status -> Job.result <| combineResults status exitResult) <|>?
                (Alt.always() >>%? exitResult)

            running()
        >>= Ch.give req.ReplyCh) 
|> start
```

I thought that it's safe to start long running or even never returning jobs because they are GC-ed when they are the only objects referencing the `Alt`s they are synchronizing on. However, `timeOut xx` is not such an `Alt`, so, as I understand, `timedOut` ivar is hold by long running  `start (timeOut req.Timeout >>=? fun _ -> timedOut <-= ())` and it prevents all the object to be GC-ed? If I'm right, what solution could you recommend?

**Comment by VesaKarvonen** [comment]
Hmm... Looking at the code it is not immediately clear to me why the commented out timeout should cause a leak, because it appears to be a one shot timeout.  *I'll keep looking into this.*  How long are the timeouts?

A timeout does keep the continuation of the timeout alive until the timeout expires.  Timeouts are removed from the timer priority queue as they expire.  So, if the timeout period is extremely long, then it could be that you see a build up of some garbage.  Still the timeout here shouldn't keep the process runners and file readers live, because the continuation of the timeout does not refer to the process runner or the file reader.  So, it seems to me that something else is going on here.

Also, if you have loop that always sets up a timeout and never commits to some other alternative, then you definitely have a leak.

Note that you can simplify things a bit by using a promise rather than an ivar for the timeout:

```fsharp
let timedOut = Promise.Now.delay (timeOut req.Timeout)
```

The file reader could also be simplified.  Here is one possible draft of how it could look:

```fsharp
module File =    
    open System.IO

    [<NoComparison; NoEquality>]
    type FileReader =
        { /// Available for picking when a new line appeared in the file or when
          /// an error is signaled by the reader process.
          NewLine: Alt<string> 
          /// A job that closes the reader and disposes the file.
          Close: Job<unit> }
        interface IAsyncDisposable with
            member x.DisposeAsync() = x.Close

    /// Reads a text file continuously, performing non-blocking pooling for new lines.
    /// It's safe to call when file does not exist yet. When the file is created, 
    /// this function opens it and starts reading.
    let startReading (path: string) : FileReader =
        let newLine = mb()
        let close = ivar()
        let error = ivar()

        let rec openReader () =
          if not (File.Exists path) then
            timeOutMillis 500 >>=? openReader <|>?
            close :> Job<_>
          else
            Job.using <| new FileStream (path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite) <| fun file ->
            Job.using <| new StreamReader (file) <| fun reader ->
            let rec loop () =
              (reader.ReadLineAsync () |> Task.awaitJob |> Promise.Now.delay >>=? fun line ->
               newLine <<-+ line >>= loop) <|>?
              close
            loop ()

        start (Job.tryInDelay openReader
                <| Job.unit
                <| IVar.fillFailure error)

        { NewLine = newLine <|>? error
          Close = IVar.tryFill close () }
```

The style difference to the original is that this just uses ordinary linear control flow where possible.

Note that the close/dispose pattern here is not 100% bullet-proof, because it does not wait for the server to actually close.

One change here is that this version also reports potential exceptions to the user via the `NewLine` alternative.  The `Task.awaitJob` functions comes from under `Hopac.Extensions`.

**Comment by VesaKarvonen** [comment]
Actually, the timeout continuation does keep a reference to the close operations of process runner and file reader, because of the `usingAsync` call.

Where do the `ObjectPool` objects come from?  They don't seem to come from the process runner or the file reader.  Could the issue be there?

The pattern of having a server synchronizing on a single `Ch.give req.ReplyCh` operation is also a bit suspect on its own, because it requires that the client that sent the request is still taking the reply from the server or the server will not be able to give the reply.

**Comment by vasily-kirichenko** [comment]
Thanks! 

The timeouts is very long - 10 hours. This server processes ~40K requests in that period, so roughly the same number of object are hold at any moment. That's not catastrophic, but I'd prefer to get rid of it.

Thanks for the file reader, I'll explore and test it tomorrow (I'm very tired at the moment). 

As a side note, I find memory leaks to be the main difficult part of programming with Hopac. It's very hard to say whether the code has leaks or not both reading it or looking at memory profilers reports. Maybe you have some pro tips on how to find leaks? Maybe Hopac could include some internal diagnostics? I'm close to write tests which would run SUT, then check that's no objects of some types is stuck in memory.

**Comment by VesaKarvonen** [comment]
I think that this issue with timeouts not being cleaned up eagerly enough is troublesome enough that it needs to be addressed.  This is something that has crossed my mind earlier, but wasn't sure whether it could be a real problem.

There are at least two issues here that need to be addressed in separate ways.  First of all, the fact that *abandoned* timeouts, i.e. timeouts that are introduced as a part of non-deterministic choice, but some other alternative is committed to instead, are not cleaned up eagearly enough is something I consider as a bug.  I think that a semi lazy approach where the insertion of a new timeout deletes abandoned timeouts encountered during insertion should be good enough.

However, in this case the timeout isn't actually abandoned.  A separate thread is spawned that waits only for the timeout so there the timeout is not directly used in a non-deterministic choice that would cause the timeout to be marked as abandoned.  Now that I think about it, the code could be written roughly like this:

```fsharp
            let timedOutOrExited = ivar()
            start (timeOut req.Timeout <|>? timedOutOrExited >>=? IVar.tryFill timedOutOrExited)
// ...
            running()
        >>= Ch.give req.ReplyCh >>= IVar.tryFill timedOutOrExited) 
```

This way the timeout is part of a non-deterministic choice, and becomes abandoned at the point that the request is serviced.  After the timer priority queue is changed to more eagerly clean up the abandoned timeouts, the leak should be gone.

About leaks.  Yes, I think some diagnostic tools might be worth writing, although I'm not sure what kind of diagnostics tools would be most useful&mdash;for the timeout issue I mentioned earlier, a static analyzer could be written, but that is probably quite a bit of work.  My experience is that GC'in jobs "just works" most of the time, **but**, on the other hand, I have rather intimate knowledge of how things work and other users don't have.  I've have also encountered a couple of cases where I expected things to be GC'ed, but, upon closer analysis, had written the logic so that it wasn't possible.

**Comment by VesaKarvonen** [comment]
@vasily-kirichenko, please test with the `timedOutOrExited` approach and the latest sources to see if they fix the issue.

**Comment by vasily-kirichenko** [comment]
I tested it. The leak has completely gone. Cool! :)

I also replaced my `File` with yours with the following change:

```fsharp
let rec openReader () =
  let readLineAlt (file: StreamReader) : Alt<string> = Alt.delay <| fun _ -> 
    if file.EndOfStream then Alt.never()
    else file.ReadLineAsync() |> Task.awaitJob |> memo :> _

  if not (File.Exists path) then
    timeOutMillis 500 >>=? openReader <|>?
    close :> Job<_>
  else
    Job.using <| new FileStream (path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite) <| fun file ->
    Job.using <| new StreamReader (file) <| fun reader ->
    let rec loop () =
      (readLineAlt reader |> memo >>=? fun line ->
        newLine <<-+ line >>= loop) <|>?
      close
    loop ()
```
The problem was that `reader.ReadLineAsync()` returns `null` when it reaches end of file, which should not be pushed to clients.

What's the purpose of `memo` in `file.ReadLineAsync() |> Task.awaitJob |> memo`?

Could you elaborate on error handling in Hopac? It seems you don't use either exceptions nor the Either monad. My team have adopted the latter approach and quite happy with it (with help with several computation expression builders from ExtCore library like `Choice`, `AsyncChoice`, `ProtectedState` and so on https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/Control.fs#L1862-L1896).

**Comment by VesaKarvonen** [comment]
Nice to hear that the leak is now gone!

The `memo` is there only to switch from the type `Job<_>` to `Alt<_>` to make it possible to combine it with the `close` alternative.  Semantically it means that the job `file.ReadLineAsync() |> Task.awaitJob` will be started as a separate concurrent job at the point when the result of the memoized alternative is first requested.

Note that when one converts a `Job<_>` to an `Alt<_>` using `memo`, there is no way to cancel the alternative: after it is first requested, it will be evaluated to completion.  In this case there should be no need to cancel the last read operation, but, in the general case, you cannot just convert jobs to alternatives and expect them to behave well when used in a non-deterministic choice.

Error handling in Hopac could mean either internal error handling within Hopac or error handling when programming with Hopac.

Internally, Hopac has only minimal needs for error handling as there are only a few operations that can "fail" (e.g. trying to fill an ivar twice).  There are many places *internally* in Hopac where exceptions must not be (and are not) raised.  However, there is a need to guard against exceptions raised by user code and to provide a means for user code to deal with such exceptions.  E.g.

```fsharp
let raisingJob: Job<unit> = Job.delay <| fun () -> failwith "Got you!"
```

needs to be handled and for that purpose constructs like `Job.tryIn` are provided.  The way these work is much like with `Async`: there is an error continuation that will be called in case a job raises an exception and then the exception will be propagated through the chain of exception handlers.  If no user code catches the exception, e.g. `start raisingJob`, then the exception will be passed to a top-level handler, which is actually started as a separate concurrent job, see

http://hopac.github.io/Hopac/Hopac.html#def:field%20Hopac.Scheduler.Create.TopLevelHandler

which, by default, just prints a message to the console, but you can replace the top-level handler (though it is a bit tricky at the moment), if you need to use a different mechanism for reporting such unexpected situations.  (Hmm... I think the top-level handler and the mechanism by which messages are written to the console should perhaps be made slightly more easily replaceable.)

The more general question is how to do error handling with Hopac.  You can use a variety of approaches.  As describe above, Hopac provides exception handling support: you can write jobs that raise exceptions and you can handle those exceptions.  I particularly recommend using `Job.tryIn` and `Job.tryInDelay` for that purpose as they make it easy to have just the right tail-call properties.

I think that exception handling is nice when it is indeed used to deal with situations that the program doesn't need to be able to handle.  Depending on the program, that can mean many things.  In such a case, you typically just need to make sure that the program properly releases critical resources when the unexpected exception happens.

When your program really needs to be robust against certain kinds of failures, it is often better to use something more than just basic exception handling.  The problem with exception handling is that it is mostly "invisible" and "unchecked" in the sense that you get no type errors if you forget to add an exception handling clause somewhere.  So, where possible and necessary it can be better to use error handling techniques that allow the compiler to help.  The `Either` monad is one example of that and you should be able to write `JobChoice` monad on top of `Job`.

**Comment by vasily-kirichenko** [comment]
Thanks for the explanation. 
I was just thinking about implementing `JobChoice` :)

**Comment by vasily-kirichenko** [comment]
I almost implemented `JobChoiceBuilder`, but stuck with `For` operation. Could you please take a look at https://github.com/Hopac/Hopac.Extras/blob/master/src/Hopac.Extras/Control.fs#L38-L41?

**Comment by VesaKarvonen** [comment]
I think you want it to have semantics like this:

```fsharp
  member job.For (xs: seq<'x>, x2uJ: 'x -> Job<Choice<unit, 'e>>) : Job<Choice<unit, 'e>> =
    Job.using <| xs.GetEnumerator() <| fun enum ->
    let rec loop () =
      if enum.MoveNext ()
      then x2uJ enum.Current >>= function
            | Ok () -> loop ()
            | fail -> Job.result fail // Fail the whole loop as soon as an iteration fails
      else Job.result <| Ok ()
    loop ()
```

**Comment by vasily-kirichenko** [comment]
Thanks!
