### ISSUE TITLE
return bool from DisposeAsync

### ISSUE THREAD

**Issue by letrec** [Hopac/Hopac#57]
Would it make sense to change the signature 
from
```F#
DisposeAsync: unit -> Job<unit>
```
to
```F#
DisposeAsync: unit -> Job<bool>
```
?

**Comment by VesaKarvonen** [comment]
Hmm... What would be the meaning of the result?  How would the result be used?

`IAsyncDisposable`[*](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.IAsyncDisposable) is modelled after `IDisposable`:

```fsharp
type IDisposable =
  abstract Dispose : unit -> unit
```

By simply making the `Dispose` operation asynchronous:

```fsharp
type IAsyncDisposable =
  abstract DisposeAsync: unit -> Job<unit>
```

The idea with this change is to allow the operation returned by `DisposeAsync` to communicate, in a non-blocking manner, with the asynchronous entity being disposed.

I think that usually one simply wants to make sure that a resource is disposed and the dispose operation should be idempotent (running it multiple times should be the same as running it once).  The idempotency suggests that a better type might be a `Promise<unit>`, because it enforces at the type level that the operation will only be performed once, but, in this case, the extra guarantee doesn't seem to mean much.

**Comment by letrec** [comment]
The result would indicate that invocation of the DisposeAsync method has the effect of disposal.
It might save a bit of memory for disposable composites:
```F#
type IAsyncDisposable =
  abstract DisposeAsync: unit -> Async<bool>

type Composite(d1 : IAsyncDisposable, d2 : IAsyncDisposable) =
    interface IAsyncDisposable with
        member this.DisposeAsync() = async {
            let! disposed = d1.DisposeAsync()
            if disposed then
                // this is a first disposal, so need to dispose of the second disposable
                let! _ = d2.DisposeAsync()
                return true
            else
                return false }
```

**Comment by vasily-kirichenko** [comment]
@letrec I agree with Vesa: `IDisposable`/`IAsyncDisposable` implementations should be idempotent. Otherwise, you end up with complicated, error prone hierarchy of such methods, like one you showed above.

**Comment by letrec** [comment]
Returning a bool doesn't make it less idempotent and doesn't change the semantics, but merely provides more information for those who may benefit from it and can be ignored by everyone else.
But this is a feature that ca be easily lived without.

**Comment by polytypic** [comment]
Thanks for the suggestion and feedback!  I think that it is best to keep the signature as close to the synchronous version.
