### ISSUE TITLE
Strange job behavior with Thread.Sleep inside

### ISSUE THREAD

**Issue by vasily-kirichenko** [Hopac/Hopac#58]
```fsharp
let started = ivar()
let finished = ivar()
job { 
    do! started <-= ()
    return! timeOutMillis 5000 
}
>>. IVar.fill finished () 
|> start

start (IVar.read started >>. job { printfn "Started." })
start (IVar.read finished >>. job { printfn "Finished." })
```
This works as expected:
```
Started.
[5 seconds pause]
Finished.
```
```fsharp
let started = ivar()
let finished = ivar()
job { 
    do! started <-= ()
    Thread.Sleep 5000 // <-------------
}
>>. IVar.fill finished () 
|> start

start (IVar.read started >>. job { printfn "Started." })
start (IVar.read finished >>. job { printfn "Finished." })
```
This outputs:
```
[5 seconds pause]
Started.
Finished.
```
What's going on?

**Comment by VesaKarvonen** [comment]
What happens here is that the first `start` immediately starts running the given job on the current thread and, because it only performs a couple of non-blocking operations it gets fully executed on the current thread and the two `start` operations that follow are executed only after the first one has finished.

Looking at the docs, I think that the current documentation of [start](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.TopLevel.start) is poorly worded.

Basically, `start` is what you need/want to use when
* you wish to immediately perform some operation and/or
* you know that the job will almost immediately wait for communication with some other job.

In the first case, you cannot use `queue`, because then there is no guarantee that the operation will be performed immediately.  Consider the following code:

```fsharp
ch <-- 1 |> queue
ch <-- 2 |> queue
```

Because the above uses `queue` rather than `start` it is not guaranteed that the message `1` would be on the channel before `2`.  This is the case where `start` must be used (if/when the order matters).

In the second case you may prefer `start` over `queue`, because `start` has lower overhead.  For example, if you spawn a concurrent server that basically immediately waits for messages from clients, then you should probably use `start` (or `server`), because it has lower overhead.  However, it is also ok to use `queue` to spawn a server.

On the other hand, if
* you wish to spawn multiple concurrent jobs, to take advantage of parallelism,
* you wish to offload work from the current job or thread, or
* you are spawning jobs that will perform substantial amounts of work before waiting for communication,
then you will likely need/want to use `queue`.  `queue` doesn't immediately perform any part of the given job on the current thread, but simply queues it for later execution on some Hopac worker thread.

In the case that you are asking about, you are spawning multiple concurrent jobs and the first job performs substantial work, so it should be `queue`ed rather than `start`ed.  In this case the other two jobs immediately wait for communication with the first thread, so it is ok, and likely faster, to use `start` to spawn the other two jobs.

**Comment by vasily-kirichenko** [comment]
Thanks for the explanation. So, `start` is equivalent to `Async.StartImmediately` and `queue` - to `Async.Start`.

I replaced `start` with `queue`:

```fsharp
let started = ivar()
let finished = ivar()
job { 
    do! started <-= ()
    Thread.Sleep 5000
}
>>. IVar.fill finished () 
|> queue

start (IVar.read started >>. job { printfn "Started." })
start (IVar.read finished >>. job { printfn "Finished." })
```

And it has not helped. I paused while it's sleeping and it seems only one Hopac thread worked:

![image](https://cloud.githubusercontent.com/assets/873919/6546189/60430388-c5bb-11e4-9187-2b2939c62ca9.png)

**Comment by vasily-kirichenko** [comment]
Aha. I added a `Job.delay` here
```fsharp
start (Job.delay <| fun _ -> IVar.read started >>. job { printfn "Started." })
```
and everything OK now. I'm not sure I understand why.

**Comment by vasily-kirichenko** [comment]
Another question is about constant number of worker threads. Currently, if all the threads are blocked, nothing executes. For example, following code creates (CPU cores number * 2) jobs each of which sleeps for 5 seconds:

```fsharp
let n = Environment.ProcessorCount * 2
let started = Latch n
let finished = ivar()
for _ in 1..n do
    job { 
        do! Latch.decrement started
        Markers.WriteFlag "Start sleeping"
        Thread.Sleep 5000 
    } |> queue
```
It results with serialized execution:

![image](https://cloud.githubusercontent.com/assets/873919/6546275/1112ea5e-c5bf-11e4-9d11-ac69752b1b97.png)

Although it's a contrived example, it's not extremely unlikely situation when you perform a number of  blocking calls (poor IO api etc.), and it'd lead to the entire application to stop working. Maybe the `ThreadPool` algorithm when it creates a new thread (each 1 second?) if there are tasks to execute but no free threads, is not such stupid? What do you think?

**Comment by VesaKarvonen** [comment]
Looking at this more closely, I think the issue that happens with sleep here is that the second job (that prints "Started."), gets queued after the first job and the way the work distribution works currently means that it cannot be continued by another worker thread.  I will be looking into changing the work distribution mechanism to make this possible.  Based on some experiments, I would expect to see a 10%-20% increase in work distribution overhead.  For most benchmarks and real applications this is unnoticeable, but will be visible in benchmarks like Fibonacci, Ping-Pong and ThreadRing.

The problem with the other question is that increasing the number of threads unfortunately does not increase the number of CPU cores. :) So, what you get that way will be the kind of trashing that you get with Async+ThreadPool.  I don't think that ThreadPool and Async/async-await can guarantee that a particular work item/async workflow gets CPU time.  Adding worker threads, like ThreadPool does, only slightly mitigates the problems.  The way I would put it, the way ThreadPool has been designed is to try to hide problems with badly written programs.

If you have some things that really must get CPU time, meaning that the cooperative model doesn't work in that case, then I would recommend using a difference scheduling strategy for such things&mdash;possibly one should spawn separate (native) threads or even separate processes for such things.

**Comment by vasily-kirichenko** [comment]
Thanks for explanation, I agree now.

**Comment by ArbilGit** [comment]
I'm having a similar issue and have narrowed it down to this:

    let jb = job{
        printfn "begin"
        System.Threading.Thread.Sleep 1000
        printfn "end"
    }
    start (Job.Ignore (jb<*>jb))

The jobs are run sequentially while I need them to run in parallel. Is there a way to make it so? I've trawled through the documentation but without success.

**Comment by VesaKarvonen** [comment]
@ArbilGit I pushed an implementation of `isolate` as a quick potential workaround for this issue.  Basically, you can wrap expensive calls as `isolate <| fun () -> expensiveSyncCall args`.  Could you try and see if this helps with your case?

**Comment by ArbilGit** [comment]
I can confirm it solves both the synthetic example above and my real issue (I launch the job as a `Promise`). Thanks! I really appreciate your timely help and it is not the first time you give it.

Can you give some guidelines, perhaps in the docs, on when to use `isolate`, or is it just a stop-gap measure?
