### ISSUE TITLE
Document all infixes

### ISSUE THREAD

**Issue by slav** [Hopac/Hopac#61]
There're numerous infixes not documented in [https://github.com/Hopac/Hopac/blob/master/Docs/Operators.md]. For example the ones ending with ? - |>>?, >>%?, >>!? and so on. Being new to Hopac it's hard to figure out what they are and what infixes are still missing.

Please add missing infixes, preferably with explanation/when to use each.

**Comment by VesaKarvonen** [comment]
Essentially all of the infix operators are optional in that you can always avoid them, but using the infix operators you can often make your code more concise and get better performance.

All of the infix operators are briefly documented in the reference manual:

* [Job.Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Job.Infixes),
* [Alt.Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Alt.Infixes),
* [Promise.Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Promise.Infixes), and
* [Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Infixes).

Note that the [Job.Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Job.Infixes), [Alt.Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Alt.Infixes), [Promise.Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Promise.Infixes) are all variations of a theme, so to speak, while the [Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Infixes) are unrelated.

I hope the documentation on [Infixes](http://hopac.github.io/Hopac/Hopac.html#dec:module%20Hopac.Infixes) is sufficient to understand how to use them.  They are just symbolic variations of various message passing operations.

To understand how and when to use the themed operations, you need to understand the essential differences between the types `Job<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Job), `Alt<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Alt) and `Promise<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Promise). Which infix operations you then use depends on the type of operation you are constructing.

The `Job<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Job) type is like `Async<'x>`[*](https://msdn.microsoft.com/en-us/library/ee370518.aspx) and forms a monad with the `Job.result`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Job.result) and `Job.bind`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Job.bind) aka `Job.Infixes.>>=`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Job.Infixes.%3E%3E=) operation.  You build values of type `Job<'x>` to specify a linear thread of execution.  Primitive values of type `Job<'x>` are essentially simple message passing operations (synchronous or asynchronous) and with the monadic operators you can build a sequence (or a "workflow") of such operations.

Values of type `Alt<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Alt), on the other hand, are build to specify selective synchronous operations.  Note that `Alt<'x>` is a subtype of `Job<'x>`.  The difference between a `Job<'x>` and `Alt<'x>` is that the latter provides additional operations, such as `choose`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.choose) and `withNack`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.withNackJob) for combining operations.  Those additional forms of composition can not be supported by all `Job<'x>` operations.  Primitive values of type `Alt<'x>` are essentially simple synchronous message passing operations and with the `Alt<'x>` specific operations you can build more complex selective synchronous operations.  Unlike with the `Job<'x>` type, there is no monad for the `Alt<'x>` type and you do not define a linear control flow with values of the `Alt<'x>` type, but rather you define more complex selective synchronous operations.  The `Alt<'x>` type basically forms a monoid with the `never`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.never) and `choose`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.choose) aka `<|>?`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Alt.Infixes.%3C|%3E?) operations.

So, basically, with the `Job<'x>` type you define independent threads of execution and with the `Alt<'x>` type you define operations through which those independent threads communicate with each other.

The `Promise<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Promise) type is a subtype of `Alt<'x>` and represents kind of one shot memoized operations.  In many contemporary approaches to concurrency in sequential languages (such as C#), promises are almost the only thing provided and that typically leads to [problems](http://tomasp.net/blog/csharp-async-gotchas.aspx/).  In Hopac, however, promises are relatively rarely used.  For linear control flow, `Job<'x>` values are preferable as they can be executed much faster, because they are not unnecessarily memoized.  For communication purposes promises only provide for a simple form of non-deterministic choice, which is sometimes sufficient (e.g. [choice streams](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Stream.Stream)), but the `Alt<'x>` type provides for more general communication patterns.  Promises are useful for basic parallelism, however.

**Comment by slav** [comment]
@VesaKarvonen - thank you so much for taking the time to explain. The Operators document seems to be a quick reference, which is why I suggested to add missing operators. Perhaps asking additional doc for each is too much, and it's better to just reference the full documentation?
