### ISSUE TITLE
Working with Tasks

### ISSUE THREAD

**Issue by slav** [Hopac/Hopac#63]
I have 3 questions
* What is recommended way to communicate out of regular task with a job? Imagine task is started by API server as async method and it's trying to get the job to do the work.
* What is the recommended way to handle IO completion? In .NET most of the time IO can be done through Task which would prevent thread blocking while IO is taking place (and continue in IO completion ports threadpool).
* There's Mailbox primitive for unbound, async communication channel. Is there a primitive for bound, async comm channel? Or you recommend just custom implementation as in BoundedMb?

Thank you.

**Comment by slav** [comment]
Forgot to ask. Is there any support to have a registry of global channels, to be able to find channel by unique name from any point of application? If not, how would you recommend handle it?

For example, an API method needs to call job to do some work. What would be the best method to find the channel to contact the job?

**Comment by VesaKarvonen** [comment]
> There's Mailbox primitive for unbound, async communication channel.  Is there a primitive for bound, async comm channel?

No, there is currently no primitive async bounded channel in Hopac.

> Or you recommend just custom implementation as in BoundedMb?

It shouldn't be too difficult to implement using existing primitives and that is what I'd recommend for starters.  If async bounded channel is really needed and an implementation made on top of the existing Hopac primitives is too slow, then a primitive implementation could certainly be written and added.

BTW, as docs say, the current `BoundedMb` is [not a primitive implementation](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.BoundedMb) and if it becomes a bottleneck, then a primitive implementation can certainly be written.

Speaking of choice of communication primitives...  I tend to mostly use just synchronous channels, ivars and mvars.  Synchronous channels are as lightweight as can be (just a single small object), tend to perform and behave predictably (as there is no buffering), provide a kind of symmetry of communication, and tend to compose most nicely when used as communication mechanisms with Hopac made concurrent entities.

> Forgot to ask.  Is there any support to have a registry of global channels, to be able to find channel by unique name from any point of application?

No, there is currently no built-in support for such a registry in Hopac.

> If not, how would you recommend handle it?

If you really need one, I'd recommend implementing one yourself for starters.

> For example, an API method needs to call job to do some work.  What would be the best method to find the channel to contact the job?

What I would recommend is to simply pass the necessary communication details to the API thing as parameters at appropriate moment (e.g. construction time).

I might be misreading between the lines, but it sounds a bit like you are thinking with the mindset that jobs are expensive and you need to have globally accessible jobs that have queues to perform specific chores (e.g. `InputVerifier`, `RequestProcessor`, `ReplySender`, ...).  If so, I would recommend rethinking the approach.  There is a section in the Erlang Programming book by Cesarini and Thompson that discusses ways to structure concurrent programs using Erlang.  The same discussion applies to Hopac.  Namely, just spawn new jobs for end-to-end processing (i.e. `VerifyInput >=> ProcessRequest >=> SendReply`) and use server jobs with which you communicate via message passing only when you have some resource that needs to be accessed in a serialized fashion.

So, you should use dedicated server jobs when you have some resource or state to which access must be serialized (e.g. you don't want to write output to a log file from multiple threads in parallel, because the output would be garbled - you must serialize writes to the log).  You then wrap such serialized resources as concurrent objects with which you communicate via jobs and alts provided by the API of the concurrent object (underneath those jobs and alts perform message passing operations).  As jobs are lightweight, you can typically have as many (just one or more) such concurrent objects as you want and you can pass those concurrent objects as parameters.

The `BoundedMb` implementation, for example, is a really simple example of a concurrent object.  A bounded mailbox serializes access to a queue of messages. You can create one or more bounded mailboxes and communicate with them via the operations, represented as alts, provided by the bounded mailbox module.  That sort of design readily extends to more complex concurrent objects that need to serialize access to something.

On the other hand, when you have some end-to-end processing to do, then you should just start a new job to perform it.  Don't try to cache and pool/reuse jobs to perform end-to-end processing, because by doing so you will only artificially limit the inherent concurrency in your application.

> What is recommended way to communicate out of regular task with a job? Imagine task is started by API server as async method and it's trying to get the job to do the work.

I would recommend representing server jobs as first-class objects with some clearly defined operations:

```fsharp
type ServerType

module ServerModule =
  ...
  val nonSelectiveOperation: ServerType -> Parameters -> Job<Result>
  ...
  val selectiveOperation: ServerType -> Parameters -> Alt<Result>
```

To actually perform an operation, you would obtain a reference to the server object of `ServerType` type, call a function to construct the desired operation and then execute the operation.  With a Hopac job, you can directly execute `Job<'x>` and `Alt<'x>` operations.  In other contexts you can convert those to `Task<'x>` or `Async<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Extensions.Async.Global.ofJob) operations and run them or you may use `queue`, `start` or `run` (which should generally be avoided as it is a blocking and potentially deadlocking operation).

> What is the recommended way to handle IO completion?  In .NET most of the time IO can be done through Task which would prevent thread blocking while IO is taking place (and continue in IO completion ports threadpool).

You should avoid blocking in Hopac jobs and use async versions of IO operations. You can execute/bind/await for `Task<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:static%20member%20Hopac.Extensions.Task.awaitJob) and `Async<'x>`[*](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Extensions.Async.toJob) operations inside jobs.

**Comment by slav** [comment]
Thank you so much @VesaKarvonen for taking the time to explain. I should've provided more concrete examples to show what I'm asking. Here's what I'm facing:

1. I have an external event stream. Inside my app there's subscriber that polls for messages. When new messages arrive, subscriber would dispatch message to correct job to handle (there're a lot of jobs, partitioned by id). My worry is that one job might get stuck processing previous message, then dispatcher is blocked waiting for it to accept the next message, thus not being able to process and dispatch messages to other jobs. With an async queue per job this gets solved, but then for unbounded queue there's risk of an OutOfMemory. I'd much rather dispatcher notice that the queue has overflow and did something about it (restart job and notify about it). But perhaps this isn't the right approach?
This is very similar to actor model with supervision, at least in current design.

2. With API server, here's what I essentially need to do (in C# for now):
```
async ProcessRequest( Model request )
{
   await ch.Send( request ); // pass message to a job through channel and await it's completion
}
```
What would be the best way to do this? I could start a job instead of using existing ch. But the critical question is about how to await, since that's what frees up the thread in .NET async/TPL world. It sounds like I need revers of Task.awaitJob?

**Comment by VesaKarvonen** [comment]
> Thank you so much @VesaKarvonen for taking the time to explain.  I should've
> provided more concrete examples to show what I'm asking.  Here's what I'm
> facing:

Hmm... I feel that the additional details only open more questions on my part

> I have an external event stream.  Inside my app there's subscriber that polls
> for messages.  When new messages arrive, subscriber would dispatch message to
> correct job to handle (there're a lot of jobs, partitioned by id).

This sounds like some form of demultiplexing.  Does each job correspond to some kind of logical thread that maintaints its own state?

> My worry is that one job might get stuck processing previous message

Getting stuck sounds a bit vague.

What does it mean to get stuck?
Why would a job get stuck?
How do you know the job is stuck?

Can it be made so that jobs report errors reliably rather than get stuck?
If not, why not?

> then dispatcher is blocked waiting for it to accept the next message, thus not
> being able to process and dispatch messages to other jobs.  With an async
> queue per job this gets solved, but then for unbounded queue there's risk of
> an OutOfMemory.  I'd much rather dispatcher notice that the queue has overflow
> and did something about it (restart job and notify about it).

Note that with a `BoundedMb` you can, for example, try to queue a message with a timeout:

```fsharp
Alt.choose [
  BoundedMb.put eventHandlerJobBoundedMb event >>=? fun () ->
    succesfullyQueuedEvent ()
  timeOutMillis 10 >>=? fun () ->
    couldNotQueueEventIn10ms_DealWithIt () ]
```

As long as the buffer of a `BoundedMb` is not full, a `put` will complete almost immediately, so the above kind of pattern allows one to detect when the buffer of the bounded mailbox is full.

> But perhaps this isn't the right approach?  This is very similar to actor
> model with supervision, at least in current design.

I can't really suggest any specific approach, because I don't know what are the acceptable and ideal ways to deal with the events in your application.

* Is it appropriate to completely skip events?
* Is it appropriate to process events out of order?
* What are minimum and maximum times that it should take to process an event and how quickly are events being generated?
* Is there a maximum time limit on the processing of an event after with the program has essentially failed?
* Should a limit on queued events be by id or by total regardless of id?
* If the processing of an event fails, how many times (0 or more) it makes sense to retry it?
* ...

That is just to give an idea of what sort of questions need to be answered.

> With API server, here's what I essentially need to do (in C# for now):

```csharp
async ProcessRequest( Model request )
{
   // pass message to a job through channel and await it's completion
   await ch.Send( request );
}
```

> What would be the best way to do this?  I could start a job instead of using
> existing ch.  But the critical question is about how to await, since that's
> what frees up the thread in .NET async/TPL world.  It sounds like I need
> revers of Task.awaitJob?

Note that Hopac has not been designed to be C# friendly.  If you must use C# and still want to use Hopac, I would recommend creating a minimal C# friendly API in F# for the things that you need to interface with from the C# side.

It looks like you have two problem here.

First of all, the basic way to communicate in Hopac with a concurrent thing is to send it a message containing some communication object, like a channel or an ivar, that allows the concurrent thing to respond to the sender of a message. The above C# style snippet does not pass a communication object, so it cannot wait for a response.  A basic client-server protocol can be implemented in Hopac as follows:

```fsharp
let protocol request serverRequestCh = Job.delay <| fun () ->
  let replyCh = ch ()
  serverRequestCh <-- (request, replyCh) >>.
  replyCh
```

Here the idea is that what ever monster is lurking on the other end of the `serverRequestCh` channel, it can respond via the `replyCh`.  What the above does is that it implement a client-server protocol as a non-selective operation, which is kind of stupid, because the idea of the `Alt` mechanism in Hopac is to encapsulate protocols such as the above as selective operations so that they can be used in a non-deterministic choice.  Here is how the above could be wrapped as a selective operation with the server giving a reply as the commit point:

```fsharp
let protocol request serverRequestCh = Alt.guard << Job.delay <| fun () ->
  let replyCh = ch ()
  serverRequestCh <-+ (request, replyCh) >>%
  replyCh
```

And here is how it would look with the server taking a request as the commit point:

```fsharp
let protocol request serverRequestCh = Alt.delay <| fun () ->
  let replyCh = ch ()
  serverRequestCh <-- (request, replyCh) >>.?
  replyCh
```

The other problem is that you want to perform the protocol from C# and be able to do that in a non-blocking fashion.  There is a basic wrapper in Hopac for running jobs as tasks in the form of [Task.startJob](http://hopac.github.io/Hopac/Hopac.html#def:static%20member%20Hopac.Extensions.Task.startJob).  It returns a job rather than a task.  To use it outside of a job workflow, you could just `run` it:

```fsharp
let runAsTask (xJ: Job<x>) =
  Task.startJob xJ |> run
```

Now you can say:

```fsharp
let doProtocolAsTask request serverRequestCh : Task<_> =
  protocol request serverRequestCh |> runAsTask
```

Which is something you could use from C#.

**Comment by slav** [comment]
Sorry, I guess I should've been as detailed as I could from the get go.

I'm trying to model a system of entities, each entity is unique with a globally unique ID and internal state. Each entity accepts a command to do something and generates event(s) in response to that command to show how command was processed. It all comes out of CQRS pattern, where commands into the system result in events, and then in another part of the system events are replayed to get the current state of the system. There could potentially be hundreds of millions of entities, each with their own state. The state itself is result of fold function over all previous events. As new event is generated by entity, it's state is updated to be used for the next command.

In practice we're modelling warehouse processes, where each item in the warehouse is an entity, with unique id, and events represent everything that happened to the item.

Events themselves are stored in event store as a stream. At any point we can load events and replay to regenerate the state or some view, although in reality it can be time consuming if there're millions of events for specific entity. So, usually we keep the current state which we update.

To me it seems that jobs are ideal candidate to represent each entity. It can accept messages for specific entity, process it and generate event. Where blocking could come from is IO: loading state on warm up, saving event, etc. I could have millions of such jobs running in parallel to handle all commands coming into the system. I might not have all jobs started, so for an entity for whom job isn't loaded would need to be started when related command come. Also, as one job completed it's task and is waiting for result to be saved via IO, it shouldn't affect other jobs. Potentially event store DB is down or is being repartitioned to handle the load, and some of the jobs begin to wait for a long time, thus their related queue could begin to grow and if queue riches certain size it's indication that something is wrong. On the other hand sync commands with timeout would be a better way to handle this situation to indicate something is wrong.

The problem with sync, to me, is that all commands come into the system in a queue (or a couple of queues), and each carries id of the entity it's related to. Dispatcher will take command, one at a time, examine it for entity id, and send to correct job. I was thinking each job would have it's own queue to which dispatcher puts messages. This is where my questions came from. But perhaps more correct approach is for the dispatcher to start a new client-job for each command which is trying to just send command to the server-entity-job in sync manner, and as soon as server accepts message it terminates? This will result in a large number of small jobs, but from what you've said Hopac is designed to handle this?

To answer some of your questions:
* Commands cannot be ignored and need to be processed in order they come into the system.
* It should be processed at most within a second, and retrying is ok as long as event for command wasn't generated (although in many cases event duplicate event is ok if it's idempotent).

**Comment by slav** [comment]
In regard to Tasks, I didn't represent my code correctly. I'm sorry. My main question is about communicating from .NET async world to Hopac world, regardless of C# or F#. In relationship to F#:
```
async {
   // how to communicate with the job via ch here? How would I do let! result = Ch.take xCh; or do! Ch.send data correctly? In other words how would I convert Job to Async to be able to wait on it and such?
}
```

**Comment by slav** [comment]
By the way, about spawning a lot of multiple jobs to send message to the client. From looking at the code Ch uses queue in form of linked list. So, the messages will be received by the server in the order they're sent. Is this correct?

**Comment by VesaKarvonen** [comment]
I only have limited time tonight and probably no time tomorrow, but I'll try to find time and write some ideas on the more general event processing question in more detail after that.  So, just a couple of quick answers.

Note that an architecture with a single sequential stream of events has a built-in sequential bottle neck.  Assuming that event dispatching takes no time, you can have at most `time to process an event / time between events` operations running in parallel.

Hopac Jobs are quite lightweight, so, in most cases, you can have as many jobs as you need.  Hundreds of millions is a lot, though.  Let's say you need 100M entities.  With, for example, 16GB of memory that would mean roughly 170 bytes per entity.  That is close to the minimum size of a concurrent Hopac object that could perhaps do something useful on a 64-bit system.  Some of the benchmarks print out numbers on how much memory is (roughly) used per job/entity of some kind.  You might want to try running them and perhaps make some test programs yourself to consider possibilities.

Hopac provides various operations for interfacing with F# Async in the [Extensions.Async](http://hopac.github.io/Hopac/Hopac.html#def:module%20Hopac.Extensions.Async) module.  The concepts of synchronization contexts and schedulers complicate the matter, but you can likely just ignore them and say (after appropriate `open` declarations):

```fsharp
type Async with
  static member AwaitJob (xJ: Job<'x>) : Async<'x> =
    Async.Global.ofJob xJ
```

After that you can use Hopac Alts and Jobs pretty much like you'd use Tasks.  Here is a silly example:

```fsharp
let sillyExample echoReqAlt = async {
  let! maybeReq =
    Alt.choose [echoReqAlt |>>? Some; timeOutMillis 100 >>%? None] |> Async.AwaitJob
  match maybeReq with
   | Some (xCh, x) ->
     return! xCh <-- x |> Async.AwaitJob
   | None ->
     ()
}
```

Conversions and transfers between Asyncs, Tasks, Jobs, and Alts are not free. For best performance you will want to minimize the number of them.  Some of the current implementations can be optimized significantly, however.

Most of the Hopac communication primitives, including Ch, MVar, Mailbox and BoundedMb, guarantee FIFO ordering as long as the giver/taker is just one Hopac job.  For example, if you use synchronous message passing

```fsharp
do! xCh <-- x1
do! xCh <-- x2
```

the other end of the communication will, of course, observe `x1` first and then `x2`.  The same also goes for asynchronous message passing:

```fsharp
do! xCh <-+ x1
do! xCh <-+ x2
```

If you have two separate jobs running in parallel and giving/taking messages on the same channel(s) their actions can be interleaved.

**Comment by slav** [comment]
I don't think I will need to have all 100m jobs running. In most cases it's just a small set (based on ID). I think I'll just start jobs as needed, and eventually after it was inactive will shut it down.

About starting client jobs to send a message. If I understand correctly, if I start a job and loose reference to it from where I started it, as long as job is awaiting on channel for the message to get accepted it won't be garbage collected (ch references the job), but as soon as message is accepted the job will be up for GCing? Or would I want to keep reference to the client-job I started until it has a chance to pass message to server-job to avoid getting GCing?

**Comment by vasily-kirichenko** [comment]
No, a job is garbage collected when there are no refs on it, regardless of the fact that it waits for messages.
