### ISSUE TITLE
API: Task.awaitJob → Job.awaitTask?

### ISSUE THREAD

**Issue by haf** [Hopac/Hopac#77]
Transforming a task to a job should create a job that await a Task, no?

Or perhaps, `Job.ofTask`?

**Comment by VesaKarvonen** [comment]
You mean to rename the function?  Yeah, the name is probably not ideal.  Perhaps `Task.awaitAsJob` and `Job.awaitTask` would work better.  I'm wary of providing conversion sounding operations, e.g. `Job.ofTask` or `Task.ofJob`, between tasks and jobs, because they have significantly different semantics when it comes to running/starting them.

**Comment by neoeinstein** [comment]
`Async` does this as `Async.awaitTask`, so I would recommend the same convention: `Job.awaitTask`.

**Comment by polytypic** [comment]
This particular rename has been [done](http://hopac.github.io/Hopac/Hopac.html#Hopac.Job.interop).
