### ISSUE TITLE
Profiling Hopac question

### ISSUE THREAD

**Issue by ArbilGit** [Hopac/Hopac#80]
I'm using ANTS Performance to profile the basic building block of my application which is an asynchronous Http request.

```fsharp
let getReqTest (req:HttpWebRequest) = job{
	try
		req.Method <- "GET"
		use! resp = Job.fromBeginEnd req.BeginGetResponse req.EndGetResponse
		use responseStream = resp.GetResponseStream()
		use streamReader = new System.IO.StreamReader(responseStream)
		try
			return Jil.JSON.Deserialize<Resp> streamReader |> Succ
		with |ex -> return Fail ex
	with | ex -> return Ex ex}
```

And for the purpose of the test it's launched by
```fsharp
timer.Elapsed.Add(fun _ -> makeReq() |> getReqTest |>> doSomething() |> Job.Global.startIgnore)
```

First result I didn't expect is that there is no work whatsoever done in threads named `Hopac.Worker`. All work is done on multiple threads of the kind `Untitled thread` and as far as I can tell new ones are being spawned constantly. I expected everything within the `getReqTest` workflow to be executed on a Hopac thread. Is this behaviour expected?

My second question is about this chain:
![hot path](https://cloud.githubusercontent.com/assets/8169557/10869213/884fa874-80a8-11e5-82db-34b69d92effb.png)

The middle numerical column is wall clock time. CPU times are very low as expected. What I expected is that for Job functions wall time and CPU time would be equal (unless `Thread.Sleep` is called explicitly within the workflow). Is this right? I don't really understand either Hopac or the Http stack; I'd expect the `recv` function that is a leaf of that execution tree to be called by this `Jil.JSON.Deserialize<Resp> streamReader` line. The wall clock time would be then the deserialiser waiting for data. I did a brute profiling though: 
```fsharp
                stopwatch.Restart()
                let res = JSON.Deserialize<Resp> streamReader |> Succ
                "Parse: " + (w.ElapsedMilliseconds|>string)|>tracen //tracen is printing helper
                return res
```
and the times reported are basically 0, so it seems there's no sleeping on that line. What am I missing?

**Comment by vasily-kirichenko** [comment]
Yes, for following code:
```fsharp
let rec fib n = 
    if n < 2 then n
    else fib (n - 1) + fib (n - 2)
     
[<EntryPoint>]
let main argv = 
    let getReqTest (req: HttpWebRequest) = 
        job { 
            try 
                req.Method <- "GET"
                use! resp = Job.fromBeginEnd req.BeginGetResponse req.EndGetResponse
                use responseStream = resp.GetResponseStream()
                use streamReader = new StreamReader(responseStream)
                try 
                    return Choice1Of2(fib 38)
                with e -> return Choice2Of2 e
            with e -> return Choice2Of2 e
        }
    WebRequest.CreateHttp "http://google.com"
    |> getReqTest
    |> run
    |> ignore
    printfn "Done."
    0
```
`fib` is running on a CLR Worker thread, not on a Hopac thread:

![image](https://cloud.githubusercontent.com/assets/873919/10869664/ecb8d006-80c6-11e5-9a41-66769681c409.png)

**Comment by ArbilGit** [comment]
Hi Vasily, do you mean the behaviour is expected, or just that you're seeing the same thing?

**Comment by vasily-kirichenko** [comment]
Hi. I'm seeing the same thing. No idea whether such behavior is ok.

**Comment by ArbilGit** [comment]
I wonder whether the above is connected with the issue that `isolate` was pushed to fix. This runs on the main thread:
```fsharp
let jb = job{
	let rec fib n = 
		if n < 2 then n
		else fib (n - 1) + fib (n - 2)
	//do! Hopac.Timer.Global.timeOutMillis 100
	fib 45 |> ignore
	printfn "%A" "finished"}
jb |> start
```
But if you uncomment the line that yields control, it will run on a Hopac.Worker thread.

**Comment by polytypic** [comment]
Sorry for not responding to this earlier.  I'm not sure that I understand what the questions really are, so the following answers might not be what you were looking for.

> All work is done on multiple threads of the kind Untitled thread and as far as I can tell new ones are being spawned constantly. I expected everything within the getReqTest workflow to be executed on a Hopac thread.

Hopac does not spawn additional threads aside from the Hopac worker threads.  So, the threads (CLR worker threads(?)) you are seeing spawned are spawned outside of Hopac as a side effect of calling `BeginGetResponse`.

Hopac also generally does not immediately transfer the execution of a job started on an arbitrary thread to a Hopac worker thread, because transferring the execution of a job from one thread to another is not free (due to queuing overhead, thread start/stop and caching).  Basically, `queue*` operations in Hopac ensure that the given job will be queued and ultimately will start running on a Hopac worker thread and `start*` (and `run`) operations (are like `Async.StartImmediate` and) basically hijack the calling thread for (usually/hopefully) short duration after which the job will be transferred to a Hopac worker.

So, what happens is that when the request started with `BeginGetResponse` completes it ends up calling the `JobFromBeginEnd.Ready` function that you can see in the stack trace picture.  From there Hopac starts running the immediate continuation of the job on the calling thread (the thread that was spawned as a side effect of `BeginGetResponse`).

In many cases this is not a problem: the continuation just does a small amount of processing and runs into something that requires waiting or otherwise runs out of immediate work at which point the calling thread is released.  However, this behaviour can be problematic if the continuation job starts a costly synchronous operation (e.g. like the `fib` test by @vasily-kirichenko) and the calling threads must not be used for anything costly.

If this is a problem (it is not clear to me from your question whether this is a problem or whether this is just something that you find puzzling), you can avoid this in several ways.  In particular, you can use `switchToWorker`.  Also, if this would be problematic, one can write versions of `Job.fromBeginEnd` and other interop primitives that essentially do that implicitly.

Ideally it would be free to transfer work from one thread to another.  If this were the case, then it would always make sense to immediately transfer job continuations to Hopac workers.  However, the costs are quite real and I don't see any simple/easy way to avoid them (at least not with user code running on .Net), so we are left with various trade-offs to choose from.  Hopac currently aims to "run short async code blocks fast" and requires one to be more explicit in cases where synchronous blocks might mess things up (by e.g. hijacking a thread for too long).  (Well, ideally the ThreadPool would be 5-10 times faster and having Hopac worker threads would be completely unnecessary.)
